Repository DataDog/dd-trace-go, pull requests merged in 2018-09, with the labels that each got.

#328 contrib/google.golang.org/grpc: add unit test for metadata
  contrib/google.golang.org/grpc/client.go
  contrib/google.golang.org/grpc/grpc_test.go
Labels: bug, integrations

#313 contrib/google.golang.org/api: add google api integration
  contrib/google.golang.org/api/api.go
  contrib/google.golang.org/api/api_test.go
  contrib/google.golang.org/api/endpoints_gen.go
  contrib/google.golang.org/api/example_test.go
  contrib/google.golang.org/api/internal/tree.go
  contrib/google.golang.org/api/internal/tree_test.go
  contrib/google.golang.org/api/make_endpoints.go
  contrib/google.golang.org/api/option.go
Labels: feature-request, integrations

#329 contrib/go-redis/redis: make go-redis traced Client a true redis.Cmdable
  contrib/go-redis/redis/redis.go
  contrib/go-redis/redis/redis_test.go
Labels: integrations

#310 contrib/confluentinc/confluent-kafka-go: add confluent kafka integration
  .circleci/config.yml
  contrib/confluentinc/confluent-kafka-go/kafka/headers.go
  contrib/confluentinc/confluent-kafka-go/kafka/kafka.go
  contrib/confluentinc/confluent-kafka-go/kafka/kafka_test.go
  contrib/confluentinc/confluent-kafka-go/kafka/option.go
  ddtrace/ext/app_types.go
Labels: feature-request, integrations

#316 contrib/miekg/dns: add support for miekg/dns
  contrib/miekg/dns/dns.go
  contrib/miekg/dns/dns_test.go
  contrib/miekg/dns/example_test.go
  ddtrace/ext/app_types.go
Labels: feature-request, integrations

#307 contrib/syndtr/goleveldb: add leveldb integration
  contrib/syndtr/goleveldb/leveldb/example_test.go
  contrib/syndtr/goleveldb/leveldb/leveldb.go
  contrib/syndtr/goleveldb/leveldb/leveldb_test.go
  contrib/syndtr/goleveldb/leveldb/option.go
  ddtrace/ext/app_types.go
Labels: feature-request, integrations

#304 contrib/tidwall/buntdb: add buntdb integration
  contrib/tidwall/buntdb/buntdb.go
  contrib/tidwall/buntdb/buntdb_test.go
  contrib/tidwall/buntdb/example_test.go
  contrib/tidwall/buntdb/option.go
Labels: feature-request, integrations

#294 contrib/mongodb/mongo-go-driver: add mongodb tracing support
  contrib/mongodb/mongo-go-driver/mongo/example_test.go
  contrib/mongodb/mongo-go-driver/mongo/mongo.go
  contrib/mongodb/mongo-go-driver/mongo/mongo_test.go
  ddtrace/ext/db.go
  ddtrace/ext/peer.go
  ddtrace/ext/tags.go
Labels: integrations

#296 contrib/Shopify/sarama: add support for tracing the sarama kafka package
  contrib/Shopify/sarama/example_test.go
  contrib/Shopify/sarama/headers.go
  contrib/Shopify/sarama/option.go
  contrib/Shopify/sarama/sarama.go
  contrib/Shopify/sarama/sarama_test.go
Labels: feature-request, integrations

#334 contrib/google.golang.org/grpc: send gRPC status code in interceptor
  contrib/google.golang.org/grpc/client.go
  contrib/google.golang.org/grpc/grpc.go
  contrib/google.golang.org/grpc/grpc_test.go
  contrib/google.golang.org/grpc/server.go
Labels: integrations

#331 contrib/emicklei/go-restful: add go-restful integration
  contrib/emicklei/go-restful/example_test.go
  contrib/emicklei/go-restful/restful.go
  contrib/emicklei/go-restful/restful_test.go
Labels: integrations
