Repository DataDog/dd-trace-go, pull requests merged in 2018-08, with the labels that each got.

#285 contrib/aws/aws-sdk-go: add aws sdk integration
  contrib/aws/aws-sdk-go/aws/aws.go
  contrib/aws/aws-sdk-go/aws/aws_test.go
  contrib/aws/aws-sdk-go/aws/example_test.go
  contrib/aws/aws-sdk-go/aws/option.go
Labels: integrations

#278 contrib/internal/httputil: generate all possible http interfaces for the response writer wrapper
  contrib/internal/httputil/make_responsewriter.go
  contrib/internal/httputil/trace.go
  contrib/internal/httputil/trace_gen.go
  contrib/internal/httputil/trace_test.go
  contrib/internal/lists/combinations.go
  contrib/internal/lists/combinations_test.go
Labels: bug

#299 contrib/net/http: add tracing for http.RoundTripper
  contrib/net/http/option.go
  contrib/net/http/roundtripper.go
  contrib/net/http/roundtripper_test.go
Labels: feature-request, integrations

#298 contrib/k8s.io/client-go: add kubernetes integration, round-tripper
  contrib/k8s.io/client-go/kubernetes/example_test.go
  contrib/k8s.io/client-go/kubernetes/kubernetes.go
  contrib/k8s.io/client-go/kubernetes/kubernetes_test.go
Labels: feature-request, integrations

#319 ddtrace/tracer: reset payload after every transport attempt
  ddtrace/tracer/tracer.go
Labels: bug

#320 gorilla/mux: allow setting custom span options
  contrib/gorilla/mux/mux.go
  contrib/gorilla/mux/mux_test.go
  contrib/gorilla/mux/option.go
Labels: integrations

#322 ddtrace/tracer: replace headers when injecting
  ddtrace/tracer/textmap.go
Labels: bug
