Repository DataDog/dd-trace-go, pull requests merged in 2019-09, with the labels that each got.

#494 contrib/hashicorp/consul: add tracing for consul clients
  .circleci/config.yml
  contrib/hashicorp/consul/benchmark_test.go
  contrib/hashicorp/consul/consul.go
  contrib/hashicorp/consul/consul_test.go
  contrib/hashicorp/consul/example_test.go
  contrib/hashicorp/consul/option.go
  ddtrace/ext/app_types.go
Labels: integrations

#498 ddtrace/tracer: simplify channels
  ddtrace/tracer/tracer.go
  ddtrace/tracer/tracer_test.go
Labels: enhancement

#497 ddtrace/tracer: add go runtime metrics
  ddtrace/tracer/metrics.go
  ddtrace/tracer/metrics_test.go
  ddtrace/tracer/option.go
  ddtrace/tracer/option_test.go
  ddtrace/tracer/tracer.go
  ddtrace/tracer/tracer_test.go
Labels: core

#504 circleci: use go1.10 as specified in the README
  .circleci/config.yml
Labels: dev/tooling
