Repository DataDog/dd-trace-go, pull requests merged in 2019-03, with the labels that each got.

#409 ddtrace/{ext,opentracer,tracer}: allow setting span name via tag
  ddtrace/ext/tags.go
  ddtrace/opentracer/option.go
  ddtrace/tracer/span.go
  ddtrace/tracer/tracer_test.go
Labels: core, opentracing

#405 contrib/go-chi/chi: Adding functionality for go-chi/chi
  contrib/go-chi/chi/chi.go
  contrib/go-chi/chi/chi_test.go
  contrib/go-chi/chi/example_test.go
  contrib/go-chi/chi/option.go
Labels: integrations

#410 contrib/go-chi/chi: fix resource issue
  contrib/go-chi/chi/chi.go
  contrib/go-chi/chi/chi_test.go
Labels: bug

#412 contrib/gocql/gocql: improve resource computation performance
  contrib/gocql/gocql/gocql.go
Labels: integrations

#415 ddtrace/tracer: add an alias tag (analytics.event) for setting event rate
  ddtrace/ext/tags.go
  ddtrace/tracer/span.go
  ddtrace/tracer/span_test.go
Labels: integrations

#416 contrib/gocql/gocql: add NoDebugStack option
  contrib/gocql/gocql/gocql.go
  contrib/gocql/gocql/option.go
Labels: integrations, proposal
