Repository DataDog/dd-trace-go, pull requests merged in 2019-07, with the labels that each got.

#467 ddtrace/tracer: add execution tracer entries
  ddtrace/tracer/span.go
  ddtrace/tracer/tracer.go
  ddtrace/tracer/tracer_go11.go
  ddtrace/tracer/tracer_nongo11.go
Labels: core, feature-request

#466 contrib/database/sql: allow setting service name per connection
  contrib/database/sql/conn.go
  contrib/database/sql/driver.go
  contrib/database/sql/option.go
  contrib/database/sql/sql.go
  contrib/database/sql/sql_test.go
  contrib/google.golang.org/grpc/option.go
  contrib/net/http/option.go
Labels: enhancement

#472 ddtrace/tracer: add Datadog-Container-ID when information is available
  ddtrace/tracer/transport.go
  ddtrace/tracer/transport_test.go
Labels: core
