Repository DataDog/dd-trace-go, pull requests merged in 2019-02, with the labels that each got.

#394 ddtrace/tracer: WithError is no-op with nil err
  ddtrace/tracer/option.go
Labels: docs

#396 contrib/google.golang.org/grpc: Fix adding errors to spans and traces
  contrib/google.golang.org/grpc/client.go
  contrib/google.golang.org/grpc/grpc.go
  contrib/google.golang.org/grpc/grpc_test.go
  contrib/google.golang.org/grpc/server.go
Labels: bug, integrations

#401 ddtrace/tracer: add origin to span context
  ddtrace/tracer/sampler.go
  ddtrace/tracer/sampler_test.go
  ddtrace/tracer/span.go
  ddtrace/tracer/span_test.go
  ddtrace/tracer/spancontext.go
  ddtrace/tracer/spancontext_test.go
  ddtrace/tracer/textmap.go
  ddtrace/tracer/textmap_test.go
  ddtrace/tracer/tracer.go
  ddtrace/tracer/tracer_test.go
Labels: core

#400 contrib/google.golang.org/grpc: add stats handler
  contrib/google.golang.org/grpc/option.go
  contrib/google.golang.org/grpc/stats_client.go
  contrib/google.golang.org/grpc/stats_client_test.go
  contrib/google.golang.org/grpc/stats_server.go
  contrib/google.golang.org/grpc/stats_server_test.go
Labels: integrations
