Repository DataDog/dd-trace-go, pull requests merged in 2019-04, with the labels that each got.

#422 contrib/gomodule/redigo: copied from contrib/garyburd/redigo
  contrib/gomodule/redigo/example_test.go
  contrib/gomodule/redigo/option.go
  contrib/gomodule/redigo/redigo.go
  contrib/gomodule/redigo/redigo_test.go
Labels: integrations

#425 contrib/Shopify/sarama: fix CI because of breaking change
  contrib/Shopify/sarama/sarama_test.go
Labels: breaking-change

#426 ddtrace/tracer: ensure root always gets sampling priority metric
  ddtrace/tracer/span_test.go
  ddtrace/tracer/spancontext.go
  ddtrace/tracer/spancontext_test.go
  ddtrace/tracer/textmap_test.go
  ddtrace/tracer/tracer.go
  ddtrace/tracer/tracer_test.go
Labels: bug
