Repository DataDog/dd-trace-go, pull requests merged in 2019-06, with the labels that each got.

#453 internal/version: bump version to 1.16.0
  internal/version/version.go
Labels: do-not-merge/WIP

#461 contrib/olivere/elastic: add customizable resource naming
  contrib/olivere/elastic/elastictrace.go
  contrib/olivere/elastic/elastictrace_test.go
  contrib/olivere/elastic/option.go
Labels: feature-request, integrations

#462 contrib/olivere/elastic: handle gzipped body when reporting
  contrib/olivere/elastic/elastictrace.go
  contrib/olivere/elastic/elastictrace_test.go
Labels: bug, community, integrations
