Repository DataDog/dd-trace-go, pull requests merged in 2019-10, with the labels that each got.

#509 ddtrace/tracer: return no-op spans when client sampler rejects trace
  ddtrace/tracer/droppedspan.go
  ddtrace/tracer/droppedspan_test.go
  ddtrace/tracer/span.go
  ddtrace/tracer/spancontext.go
  ddtrace/tracer/spancontext_test.go
  ddtrace/tracer/tracer.go
  ddtrace/tracer/tracer_test.go
Labels: core, enhancement

#520 ddtrace/tracer: skip creating Meta and Metrics map when not needed
  ddtrace/tracer/span.go
  ddtrace/tracer/spancontext.go
  ddtrace/tracer/tracer.go
  ddtrace/tracer/tracer_test.go
Labels: core

#513 contrib/twitchtv/twirp: tracing for twirp servers
  contrib/twitchtv/twirp/example_test.go
  contrib/twitchtv/twirp/option.go
  contrib/twitchtv/twirp/twirp.go
  contrib/twitchtv/twirp/twirp_test.go
Labels: enhancement, integrations

#527 ddtrace/tracer: ensure hanging traces are flushed when stopping
  ddtrace/tracer/tracer.go
Labels: bug, core
