Repository DataDog/dd-trace-go, pull requests merged in 2020-04, with the labels that each got.

#629 contrib/internal/httputil: only set status once with WriteHeader
  contrib/internal/httputil/trace.go
  contrib/internal/httputil/trace_test.go
Labels: bug

#636 ddtrace/tracer: add WithHTTPClient and increase default HTTP timeout
  ddtrace/tracer/option.go
  ddtrace/tracer/option_test.go
  ddtrace/tracer/tracer.go
  ddtrace/tracer/tracer_test.go
  ddtrace/tracer/transport.go
  ddtrace/tracer/transport_test.go
Labels: core, enhancement

#641 contrib/gocql/gocql: avoid panics
  contrib/gocql/gocql/gocql.go
Labels: bug, integrations
