Repository DataDog/dd-trace-go, pull requests merged in 2022-10, with the labels that each got.

#1494 appsec/waf: enable linux and darwin on arm64 targets
  .github/workflows/appsec.yml
  CODEOWNERS
  internal/appsec/_tools/libddwaf-updater/update.sh
  internal/appsec/waf/lib/darwin-arm64/libddwaf.a
  internal/appsec/waf/lib/darwin-arm64/vendor.go
  internal/appsec/waf/lib/linux-arm64/libddwaf.a
  internal/appsec/waf/lib/linux-arm64/vendor.go
  internal/appsec/waf/waf.go
  internal/appsec/waf/waf_disabled.go
  internal/appsec/waf/waf_disabled_target.go
  internal/appsec/waf/waf_disabled_test.go
  internal/appsec/waf/waf_test.go
Labels: appsec

#1495 .github/workflows: do not skip system-tests cron jobs
  .github/workflows/system-tests.yml
Labels: ci

#1505 .github/workflows: add parametric tests
  .github/workflows/parametric-tests.yml
Labels: ci

#1493 internal/appsec/waf: blocking API bindings
  internal/appsec/waf.go
  internal/appsec/waf/waf.go
  internal/appsec/waf/waf_disabled.go
  internal/appsec/waf/waf_test.go
Labels: appsec

#1508 ci/appsec: run tests having DD_APPSEC_ENABLED undefined
  .github/workflows/appsec.yml
Labels: appsec, ci

#1521 codecov: replace ci status by a pr comment
  codecov.yml
Labels: ci

#1532 codecov: disable CI status checks
  codecov.yml
Labels: ci

#1523 appsec: report http.client_ip only when appsec is enabled
  contrib/gin-gonic/gin/appsec.go
  contrib/google.golang.org/grpc/appsec.go
  contrib/internal/httptrace/config.go
  contrib/internal/httptrace/config_test.go
  contrib/internal/httptrace/httptrace.go
  contrib/internal/httptrace/httptrace_test.go
  contrib/labstack/echo.v4/appsec.go
  internal/appsec/dyngo/instrumentation/common.go
  internal/appsec/dyngo/instrumentation/httpsec/http.go
  internal/appsec/dyngo/instrumentation/httpsec/ip_default.go
  internal/appsec/dyngo/instrumentation/httpsec/ip_go119.go
  internal/appsec/dyngo/instrumentation/httpsec/tags.go
  internal/appsec/dyngo/instrumentation/httpsec/tags_test.go
Labels: bug, appsec, tracer

#1459 all: create SECURITY.md
  SECURITY.md
Labels: docs

#1539 ci: enable manual dispatch on multi-os tests
  .github/workflows/multios-unit-tests.yml
Labels: ci

#1545 ci: run the apm release ci on release branches
  .github/workflows/main-branch-tests.yml
Labels: ci
