Repository DataDog/dd-trace-go, pull requests merged in 2022-12, with the labels that each got.

#1601 contrib: clarify use of UnaryInterceptor in grpc example
  contrib/google.golang.org/grpc/example_test.go
Labels: no-changelog

#1613 go.mod: change agent remote-config package enforcing our working fork
  go.mod
  go.sum
Labels: backport

#1533 internal/appsec: implement WAF actions for http/grpc
  CODEOWNERS
  contrib/gin-gonic/gin/appsec.go
  contrib/google.golang.org/grpc/appsec.go
  contrib/google.golang.org/grpc/appsec_test.go
  contrib/labstack/echo.v4/appsec.go
  internal/appsec/dyngo/instrumentation/common.go
  internal/appsec/dyngo/instrumentation/grpcsec/actions.go
  internal/appsec/dyngo/instrumentation/grpcsec/grpc.go
  internal/appsec/dyngo/instrumentation/grpcsec/tags.go
  internal/appsec/dyngo/instrumentation/grpcsec/tags_test.go
  internal/appsec/dyngo/instrumentation/httpsec/actions.go
  internal/appsec/dyngo/instrumentation/httpsec/actions_test.go
  internal/appsec/dyngo/instrumentation/httpsec/blocked-template.html
  internal/appsec/dyngo/instrumentation/httpsec/blocked-template.json
  internal/appsec/dyngo/instrumentation/httpsec/http.go
  internal/appsec/dyngo/instrumentation/httpsec/ip_default.go
  internal/appsec/dyngo/instrumentation/httpsec/ip_go119.go
  internal/appsec/dyngo/instrumentation/httpsec/tags.go
  internal/appsec/dyngo/instrumentation/httpsec/tags_test.go
  internal/appsec/dyngo/instrumentation/ip_default.go
  internal/appsec/dyngo/instrumentation/ip_go119.go
  internal/appsec/testdata/blocking.json
  internal/appsec/waf.go
  internal/appsec/waf_test.go
Labels: appsec

#1603 tracer: replaces INJECT/EXTRACT environment variable names
  ddtrace/tracer/textmap.go
  ddtrace/tracer/textmap_test.go
Labels: tracer

#1622 ci/govulncheck: use the latest stable go version
  .github/workflows/govulncheck.yml
Labels: ci

#1623 ci/govulncheck: fix and simplify the bash script
  .github/workflows/govulncheck.yml
Labels: ci

#1627 internal/remoteconfig: client error handling (backport of release-v1.45.x fixes)
  internal/appsec/remoteconfig.go
  internal/remoteconfig/remoteconfig.go
Labels: remote-config

#1631 ci: auto trigger major workflows on release branches
  .github/workflows/appsec.yml
  .github/workflows/govulncheck.yml
  .github/workflows/parametric-tests.yml
  .github/workflows/release-candidate.yml
  .github/workflows/release-start.yml
  .github/workflows/smoke-tests.yml
  .github/workflows/system-tests.yml
Labels: ci
