Repository DataDog/dd-trace-go, pull requests merged in 2022-09, with the labels that each got.

#1448 contrib/database/sql: add db service name tag and _dd.dbm_trace_injected span tag
  contrib/database/sql/conn.go
  contrib/database/sql/injection_test.go
  ddtrace/tracer/sqlcomment.go
  ddtrace/tracer/sqlcomment_test.go
Labels: enhancement

#1464 appsec: update the security event rules to v1.4.0
  internal/appsec/rule.go
Labels: appsec

#1460 appsec/waf: update libddwaf to v1.5.0
  internal/appsec/waf/include/ddwaf.h
  internal/appsec/waf/lib/darwin-amd64/libddwaf.a
  internal/appsec/waf/lib/linux-amd64/libddwaf.a
  internal/appsec/waf/waf.go
Labels: appsec

#1471 contrib/net/http: don't set request path in Route field.
  contrib/net/http/http.go
Labels: bug

#1465 readme: add an introduction to the repo content
  README.md
Labels: docs
