Repository DataDog/dd-trace-go, pull requests merged in 2023-10, with the labels that each got.

#2267 profiler: remove PprofDiff
  profiler/profile.go
  profiler/profile_test.go
Labels: profiler

#2277 conbrib/gofiber/fiber: upgrade to v2.50.0 and fix breaking change
  contrib/gofiber/fiber.v2/fiber.go
  go.mod
  go.sum
Labels: apm:ecosystem, tracer

#2279 opentelemetry: finish a span with an error if one is provided
  ddtrace/opentelemetry/span.go
  ddtrace/opentelemetry/span_test.go
Labels: otel

#2234 contrib: implement http.route in missing contribs
  contrib/dimfeld/httptreemux.v5/httptreemux.go
  contrib/dimfeld/httptreemux.v5/httptreemux_test.go
  contrib/emicklei/go-restful.v3/restful.go
  contrib/emicklei/go-restful.v3/restful_test.go
  contrib/gofiber/fiber.v2/fiber.go
  contrib/gofiber/fiber.v2/fiber_test.go
  contrib/gorilla/mux/mux_test.go
  contrib/labstack/echo.v4/echotrace_test.go
  contrib/urfave/negroni/negroni.go
  contrib/zenazn/goji.v1/web/goji.go
  contrib/zenazn/goji.v1/web/goji_test.go
Labels: apm:ecosystem

#2292 appsec: update event rules 1.7.1 -> 1.8.0
  internal/appsec/rules.go
  internal/appsec/rules.json
Labels: mergequeue-status: in_progress

#2304 contrib/(github and gopkg)/gorm: Mark as deprecated
  contrib/gopkg.in/jinzhu/gorm.v1/gorm.go
  contrib/jinzhu/gorm/gorm.go
Labels: apm:ecosystem
