Repository DataDog/dd-trace-go, pull requests merged in 2023-04, with the labels that each got.

#1846 appsec: use http client ip from external go module
  contrib/google.golang.org/grpc/appsec.go
  contrib/internal/httptrace/httptrace_test.go
  go.mod
  go.sum
  internal/appsec/dyngo/instrumentation/grpcsec/grpc.go
  internal/appsec/dyngo/instrumentation/grpcsec/tags_test.go
  internal/appsec/dyngo/instrumentation/httpsec/http.go
  internal/appsec/dyngo/instrumentation/httpsec/tags.go
  internal/appsec/dyngo/instrumentation/httpsec/tags_test.go
  internal/appsec/dyngo/instrumentation/ip_default.go
  internal/appsec/dyngo/instrumentation/ip_go119.go
Labels: appsec, tracer

#1884 ci: skip unit-of-work in fork PRs
  .github/workflows/test-apps.yml
Labels: ci

#1892 ci: fix flaky lint job
  .github/workflows/unit-integration-tests.yml
Labels: ci

#1898 ci: introduce golangci
  .github/workflows/unit-integration-tests.yml
  .golangci.yml
  contrib/99designs/gqlgen/tracer.go
  contrib/Shopify/sarama/sarama_test.go
  contrib/database/sql/internal/mockdriver.go
  contrib/database/sql/sql_test.go
  contrib/dimfeld/httptreemux.v5/example_test.go
  contrib/dimfeld/httptreemux.v5/httptreemux.go
  contrib/dimfeld/httptreemux.v5/httptreemux_test.go
  contrib/go-chi/chi.v5/example_test.go
  contrib/go-chi/chi/example_test.go
  contrib/go-pg/pg.v10/pg_go_test.go
  contrib/go-redis/redis/redis_test.go
  contrib/go.mongodb.org/mongo-driver/mongo/mongo.go
  contrib/google.golang.org/grpc/grpc_test.go
  contrib/google.golang.org/grpc/stats_server_test.go
  contrib/gorilla/mux/example_test.go
  contrib/gorilla/mux/mux_test.go
  contrib/graph-gophers/graphql-go/graphql.go
  contrib/hashicorp/vault/example_test.go
  contrib/julienschmidt/httprouter/example_test.go
  contrib/net/http/example_test.go
  contrib/net/http/http_test.go
  contrib/twitchtv/twirp/example_test.go
  contrib/twitchtv/twirp/twirp.go
  contrib/twitchtv/twirp/twirp_test.go
  contrib/urfave/negroni/example_test.go
  contrib/urfave/negroni/option.go
  ddtrace/example_test.go
  ddtrace/internal/globaltracer.go
  ddtrace/internal/globaltracer_test.go
  ddtrace/mocktracer/example_test.go
  ddtrace/opentelemetry/span.go
  ddtrace/opentelemetry/tracer.go
  ddtrace/opentelemetry/tracer_provider.go
  ddtrace/opentracer/span.go
  ddtrace/tracer/option_test.go
  ddtrace/tracer/sampler_test.go
  ddtrace/tracer/span_test.go
  ddtrace/tracer/spancontext_test.go
  ddtrace/tracer/time.go
  ddtrace/tracer/tracer_test.go
  internal/appsec/dyngo/instrumentation/grpcsec/tags_test.go
  internal/hostname/providers_test.go
  internal/log/log.go
  internal/remoteconfig/remoteconfig.go
  internal/telemetry/telemetry_test.go
  internal/telemetry/telemetrytest/telemetrytest.go
  internal/traceprof/traceproftest/app.go
  internal/traceprof/traceproftest/util.go
  profiler/internal/fastdelta/fd_test.go
Labels: ci

#1797 appsec: suspicious request blocking
  go.mod
  go.sum
  internal/appsec/appsec.go
  internal/appsec/config.go
  internal/appsec/config_test.go
  internal/appsec/remoteconfig.go
  internal/appsec/remoteconfig_test.go
  internal/appsec/ruleset_builder.go
  internal/appsec/ruleset_builder_test.go
  internal/appsec/waf.go
  internal/remoteconfig/config.go
  internal/remoteconfig/remoteconfig.go
  internal/remoteconfig/remoteconfig_test.go
Labels: appsec

#1899 ci/golangci-lint: skip google.golang.org/grpc.v12
  .golangci.yml
  CONTRIBUTING.md
Labels: ci

#1873 internal/appsec/dyngo: atomic instrumentation swapping
  go.mod
  internal/appsec/appsec.go
  internal/appsec/config.go
  internal/appsec/config_test.go
  internal/appsec/dyngo/operation.go
  internal/appsec/dyngo/operation_test.go
  internal/appsec/remoteconfig.go
  internal/appsec/remoteconfig_test.go
  internal/appsec/ruleset_builder.go
  internal/appsec/waf.go
  internal/remoteconfig/remoteconfig.go
  internal/remoteconfig/remoteconfig_test.go
Labels: appsec

#1930 ci/system-tests: more scenarios with parallel jobs
  .github/workflows/system-tests.yml
Labels: ci

#1942 ci: update linter job and add bodyclose
  .github/workflows/unit-integration-tests.yml
  .golangci.yml
  CODEOWNERS
  contrib/gin-gonic/gin/appsec_test.go
  contrib/gin-gonic/gin/gintrace_test.go
  contrib/go-chi/chi.v5/chi_test.go
  contrib/go-chi/chi/chi_test.go
  contrib/gofiber/fiber.v2/fiber_test.go
  contrib/gorilla/mux/mux_test.go
  contrib/graph-gophers/graphql-go/graphql_test.go
  contrib/labstack/echo.v4/appsec_test.go
  contrib/net/http/example_test.go
  contrib/net/http/roundtripper_test.go
  contrib/twitchtv/twirp/twirp_test.go
  contrib/urfave/negroni/negroni_test.go
  contrib/zenazn/goji.v1/web/goji_test.go
  ddtrace/tracer/log.go
  internal/httpmem/httpmem_test.go
Labels: ci
