Repository DataDog/dd-trace-go, pull requests merged in 2023-12, with the labels that each got.

#2361 contrib/google.golang.org/grpc: add hostname tag
  contrib/google.golang.org/grpc/client.go
  contrib/google.golang.org/grpc/grpc_test.go
Labels: apm:ecosystem

#2328 contrib/database/sql: prevent DBM propagation full mode with incompatible dbs
  contrib/database/sql/option.go
  contrib/database/sql/propagation_test.go
  contrib/database/sql/sql.go
  contrib/database/sql/sql_test.go
Labels: apm:ecosystem

#2381 appsec: HTTP schema extraction for API Security
  .github/workflows/system-tests.yml
  go.mod
  go.sum
  internal/apps/go.mod
  internal/apps/go.sum
  internal/appsec/appsec.go
  internal/appsec/appsec_test.go
  internal/appsec/config.go
  internal/appsec/config_test.go
  internal/appsec/listener/httpsec/http.go
  internal/appsec/remoteconfig.go
  internal/appsec/remoteconfig_test.go
  internal/appsec/rules_manager.go
  internal/appsec/trace/tagsholder.go
  internal/appsec/waf.go
  internal/appsec/waf_test.go
  internal/appsec/waf_unit_test.go
Labels: appsec

#2418 contrib: fix span start option races
  contrib/database/sql/conn.go
  contrib/database/sql/sql.go
  contrib/gin-gonic/gin/gintrace.go
  contrib/go-chi/chi.v5/chi.go
  contrib/go-chi/chi.v5/chi_test.go
  contrib/go-chi/chi/chi.go
  contrib/google.golang.org/grpc.v12/grpc.go
  contrib/google.golang.org/grpc/stats_client.go
  contrib/gorilla/mux/mux.go
  contrib/internal/options/options.go
  contrib/internal/options/options_test.go
  contrib/julienschmidt/httprouter/httprouter.go
  contrib/k8s.io/client-go/kubernetes/kubernetes.go
  contrib/labstack/echo.v4/echotrace.go
  contrib/labstack/echo/echotrace.go
  contrib/net/http/trace.go
  contrib/urfave/negroni/negroni.go
Labels: bug, apm:ecosystem

#2401 profiler: randomize when execution traces are collected
  profiler/profile.go
  profiler/profiler.go
  profiler/profiler_test.go
Labels: profiler

#2305 contrib/valyala/fasthttp.v1: add a fasthttp integration to ddtrace
  contrib/internal/fasthttptrace/fasthttpheaderscarrier.go
  contrib/internal/fasthttptrace/fasthttpheaderscarrier_test.go
  contrib/valyala/fasthttp.v1/example_test.go
  contrib/valyala/fasthttp.v1/fasthttp.go
  contrib/valyala/fasthttp.v1/fasthttp_test.go
  contrib/valyala/fasthttp.v1/option.go
  ddtrace/tracer/option.go
  ddtrace/tracer/option_test.go
Labels: apm:ecosystem, mergequeue-status: error

#2402 [CONTINT-3554] Send the `Datadog-Entity-ID` header, containing either the container-id or the cgroup inode if available
  ddtrace/tracer/transport.go
  internal/container.go
  internal/container_test.go
  internal/datastreams/transport.go
  internal/telemetry/client.go
  profiler/profiler.go
  profiler/upload.go
  profiler/upload_test.go
Labels: enhancement, team:apm-go

#2443 AIT-9184: update gotraceui to v0.3.0.
  contrib/database/sql/exec_trace_test.go
  go.mod
  go.sum
Labels: profiler

#2228 contrib/google.golang.org/grpc: add error details to span tags
  contrib/google.golang.org/grpc/grpc.go
  contrib/google.golang.org/grpc/grpc_test.go
  contrib/google.golang.org/grpc/option.go
  contrib/google.golang.org/grpc/tags.go
Labels: apm:ecosystem

#2468 tracer: handle rc deletion in dynamic config
  ddtrace/tracer/remote_config.go
  ddtrace/tracer/remote_config_test.go
Labels: mergequeue-status: in_progress
