Repository DataDog/dd-trace-go, pull requests merged in 2023-11, with the labels that each got.

#2269 contrib/globalsign/mgo: err always nil.
  contrib/globalsign/mgo/mgo_test.go
  contrib/globalsign/mgo/pipe.go
Labels: apm:ecosystem

#2318 contrib: remove jinzhu/gorm and gopkg.in/jinzhu/gorm.v1
  contrib/gopkg.in/jinzhu/gorm.v1/example_test.go
  contrib/gopkg.in/jinzhu/gorm.v1/gorm.go
  contrib/gopkg.in/jinzhu/gorm.v1/gorm_test.go
  contrib/gopkg.in/jinzhu/gorm.v1/option.go
  contrib/jinzhu/gorm/example_test.go
  contrib/jinzhu/gorm/gorm.go
  contrib/jinzhu/gorm/gorm_test.go
  contrib/jinzhu/gorm/option.go
  go.mod
  go.sum
Labels: apm:ecosystem

#2320 contrib: remove emicklei/go-restful
  contrib/emicklei/go-restful/example_test.go
  contrib/emicklei/go-restful/option.go
  contrib/emicklei/go-restful/restful.go
  contrib/emicklei/go-restful/restful_test.go
  go.mod
  go.sum
Labels: apm:ecosystem

#2321 contrib: remove garyburd/redigo
  contrib/garyburd/redigo/example_test.go
  contrib/garyburd/redigo/option.go
  contrib/garyburd/redigo/redigo.go
  contrib/garyburd/redigo/redigo_test.go
  go.mod
  go.sum
Labels: apm:ecosystem

#2326 contrib: remove zenazn/goji
  contrib/zenazn/goji.v1/web/example_test.go
  contrib/zenazn/goji.v1/web/goji.go
  contrib/zenazn/goji.v1/web/goji_test.go
  contrib/zenazn/goji.v1/web/option.go
  go.mod
  go.sum
Labels: apm:ecosystem

#2327 contrib: remove olivere/elastic.v3
  contrib/olivere/elastic/elastictrace.go
  contrib/olivere/elastic/elastictrace_test.go
  contrib/olivere/elastic/example_test.go
  go.mod
  go.sum
Labels: apm:ecosystem

#2278 contrib/google.golang.org/grpc: isolate tests using an independent rig instance instead of a shared one
  contrib/google.golang.org/grpc/appsec_test.go
  contrib/google.golang.org/grpc/grpc_test.go
Labels: apm:ecosystem

#2284 opentelemetry: embed no-op structs
  ddtrace/opentelemetry/span.go
  ddtrace/opentelemetry/span_test.go
  ddtrace/opentelemetry/tracer.go
  ddtrace/opentelemetry/tracer_provider.go
  ddtrace/opentelemetry/tracer_test.go
  go.mod
  go.sum
Labels: otel

#2339 tracer: always propagate the tracestate header
  ddtrace/tracer/textmap.go
  ddtrace/tracer/textmap_test.go
Labels: otel

#2338 feat: upgrade in-app WAF to ephemeral-capable version
  contrib/google.golang.org/grpc/appsec_test.go
  go.mod
  go.sum
  internal/appsec/appsec.go
  internal/appsec/appsec_test.go
  internal/appsec/dyngo/instrumentation/common.go
  internal/appsec/dyngo/instrumentation/grpcsec/grpc.go
  internal/appsec/dyngo/instrumentation/grpcsec/grpc_test.go
  internal/appsec/dyngo/instrumentation/grpcsec/tags.go
  internal/appsec/dyngo/instrumentation/grpcsec/tags_test.go
  internal/appsec/dyngo/instrumentation/httpsec/http.go
  internal/appsec/dyngo/instrumentation/httpsec/tags.go
  internal/appsec/dyngo/instrumentation/httpsec/tags_test.go
  internal/appsec/remoteconfig.go
  internal/appsec/remoteconfig_test.go
  internal/appsec/rule_test.go
  internal/appsec/waf.go
  internal/appsec/waf_unit_test.go
Labels: mergequeue-status: in_progress

#2353 contrib/kafka: take env variable into account to enable DSM
  contrib/Shopify/sarama/option.go
  contrib/Shopify/sarama/option_test.go
  contrib/confluentinc/confluent-kafka-go/kafka.v2/option.go
  contrib/confluentinc/confluent-kafka-go/kafka.v2/option_test.go
  contrib/confluentinc/confluent-kafka-go/kafka/option.go
  contrib/confluentinc/confluent-kafka-go/kafka/option_test.go
Labels: apm:ecosystem

#2357 contrib/aws: add go.mod to isolate contrib
  .github/workflows/apps/test-contrib-submodules.sh
  .github/workflows/unit-integration-tests.yml
  contrib/aws/go.mod
  contrib/aws/go.sum
  go.mod
  go.sum
Labels: apm:ecosystem

#2358 contrib: add go.mod to isolate contribs gqlgen, httptreemux, go-elasticsearch, cloud.google.com/go/pubsub.v1, hashicorp/consul & hashicorp/vault
  .github/workflows/unit-integration-tests.yml
  contrib/99designs/gqlgen/go.mod
  contrib/99designs/gqlgen/go.sum
  contrib/cloud.google.com/go/pubsub.v1/go.mod
  contrib/cloud.google.com/go/pubsub.v1/go.sum
  contrib/dimfeld/httptreemux.v5/go.mod
  contrib/dimfeld/httptreemux.v5/go.sum
  contrib/elastic/go-elasticsearch.v6/go.mod
  contrib/elastic/go-elasticsearch.v6/go.sum
  contrib/hashicorp/consul/go.mod
  contrib/hashicorp/consul/go.sum
  contrib/hashicorp/vault/go.mod
  contrib/hashicorp/vault/go.sum
  go.mod
  go.sum
Labels: apm:ecosystem

#2377 pull_request_template.md: explicit the need to enable or add system tests
  .github/pull_request_template.md
Labels: ci

#2383 contrib: add go.mod to isolate contribs pg, mongo-driver, gocql, fiber, redigo & gorm
  go.mod
  go.sum
  isolatecontrib.go
  v2/contrib/go-pg/pg.v10/example_test.go
  v2/contrib/go-pg/pg.v10/go.mod
  v2/contrib/go-pg/pg.v10/go.sum
  v2/contrib/go-pg/pg.v10/option.go
  v2/contrib/go-pg/pg.v10/pg_go.go
  v2/contrib/go-pg/pg.v10/pg_go_test.go
  v2/contrib/go.mongodb.org/mongo-driver/go.mod
  v2/contrib/go.mongodb.org/mongo-driver/go.sum
  v2/contrib/go.mongodb.org/mongo-driver/mongo/example_test.go
  v2/contrib/go.mongodb.org/mongo-driver/mongo/mongo.go
  v2/contrib/go.mongodb.org/mongo-driver/mongo/mongo_test.go
  v2/contrib/go.mongodb.org/mongo-driver/mongo/option.go
  v2/contrib/gocql/gocql/example_test.go
  v2/contrib/gocql/gocql/go.mod
  v2/contrib/gocql/gocql/go.sum
  v2/contrib/gocql/gocql/gocql.go
  v2/contrib/gocql/gocql/gocql_test.go
  v2/contrib/gocql/gocql/option.go
  v2/contrib/gofiber/fiber.v2/example_test.go
  v2/contrib/gofiber/fiber.v2/fiber.go
  v2/contrib/gofiber/fiber.v2/fiber_test.go
  v2/contrib/gofiber/fiber.v2/go.mod
  v2/contrib/gofiber/fiber.v2/go.sum
  v2/contrib/gofiber/fiber.v2/option.go
  v2/contrib/gomodule/redigo/example_test.go
  v2/contrib/gomodule/redigo/go.mod
  v2/contrib/gomodule/redigo/go.sum
  v2/contrib/gomodule/redigo/option.go
  v2/contrib/gomodule/redigo/redigo.go
  v2/contrib/gomodule/redigo/redigo_test.go
  v2/contrib/gorm.io/gorm.v1/example_test.go
  v2/contrib/gorm.io/gorm.v1/go.mod
  v2/contrib/gorm.io/gorm.v1/go.sum
  v2/contrib/gorm.io/gorm.v1/gorm.go
  v2/contrib/gorm.io/gorm.v1/gorm_test.go
  v2/contrib/gorm.io/gorm.v1/option.go
Labels: apm:ecosystem

#2385 contrib: remove deprecated APIs
  contrib/database/sql/conn_test.go
  contrib/database/sql/option.go
  contrib/database/sql/propagation_test.go
  contrib/database/sql/sql.go
  contrib/database/sql/sql_test.go
  contrib/google.golang.org/grpc/appsec_test.go
  contrib/google.golang.org/grpc/grpc_test.go
  contrib/google.golang.org/grpc/option.go
  contrib/net/http/option.go
  v2/contrib/cloud.google.com/go/pubsub.v1/option.go
  v2/contrib/confluentinc/confluent-kafka-go/kafka.v2/kafka_test.go
  v2/contrib/confluentinc/confluent-kafka-go/kafka.v2/option.go
  v2/contrib/confluentinc/confluent-kafka-go/kafka/kafka_test.go
  v2/contrib/confluentinc/confluent-kafka-go/kafka/option.go
  v2/contrib/gocql/gocql/gocql.go
  v2/contrib/gocql/gocql/gocql_test.go
Labels: apm:ecosystem

#2386 contrib/grpc: cleanup ignoredMethods config
  contrib/google.golang.org/grpc/option.go
  contrib/google.golang.org/grpc/server.go
Labels: apm:ecosystem

#1504 contrib/aws/{aws-sdk-go/aws, aws-sdk-go-v2/aws}: add context example
  contrib/aws/aws-sdk-go-v2/aws/doc.go
  contrib/aws/aws-sdk-go-v2/aws/example_test.go
  contrib/aws/aws-sdk-go/aws/example_test.go
Labels: apm:ecosystem

#2332 contrib/dimfeld/httptreemux.v5: parameterize redirects due to trailing slash
  contrib/dimfeld/httptreemux.v5/httptreemux.go
  contrib/dimfeld/httptreemux.v5/httptreemux_test.go
Labels: bug, apm:ecosystem
