Repository DataDog/dd-trace-go, pull requests merged in 2023-09, with the labels that each got.

#2169 contrib/labstack/echo.v4: add WithErrorTranslator Option
  contrib/labstack/echo.v4/echotrace.go
  contrib/labstack/echo.v4/echotrace_test.go
  contrib/labstack/echo.v4/option.go
Labels: apm:ecosystem

#2216 Disable profiling when run in AWS Lambda.
  profiler/profiler.go
  profiler/profiler_test.go
Labels: profiler

#2221 Create repository.datadog.yml
  repository.datadog.yml
Labels: team:apm-go

#2222 contrib/google.golang.org/grpc.v12: remove grpc.v12 contrib
  .github/workflows/govulncheck.yml
  .github/workflows/multios-unit-tests.yml
  .github/workflows/unit-integration-tests.yml
  .gitignore
  .golangci.yml
  README.md
  contrib/google.golang.org/grpc.v12/example_test.go
  contrib/google.golang.org/grpc.v12/fixtures_test.pb.go
  contrib/google.golang.org/grpc.v12/fixtures_test.proto
  contrib/google.golang.org/grpc.v12/grpc.go
  contrib/google.golang.org/grpc.v12/grpc_test.go
  contrib/google.golang.org/grpc.v12/option.go
  contrib/google.golang.org/grpc.v12/tags.go
  test.sh
Labels: v2.0

#2224 [V2 experimentation]profiler: remove WithAPIKey and WithAgentlessUpload
  profiler/options.go
  profiler/options_test.go
  profiler/profiler.go
  profiler/profiler_test.go
Labels: v2.0

#2229 ddtrace/mocktracer: use lock in String method
  ddtrace/mocktracer/mockspan.go
  ddtrace/mocktracer/mockspan_test.go
Labels: mergequeue-status: in_progress

#2225 [V2 experimentation] ddtrace/tracer: add WithAgentURL option
  ddtrace/tracer/option.go
  ddtrace/tracer/option_test.go
Labels: v2.0

#2226 profiler: enable execution traces by default for go1.21+
  profiler/go_lt_1_21.go
  profiler/options.go
  profiler/profiler_test.go
Labels: mergequeue-status: error
