Repository DataDog/dd-trace-go, pull requests merged in 2023-05, with the labels that each got.

#1957 ci/smoke-tests: update the go.sum file after go get -u
  .github/workflows/smoke-tests.yml
Labels: ci

#1968 ci: update macOS targets
  .github/workflows/appsec.yml
Labels: appsec, ci

#1682 contrib/aws/aws-sdk-go: add WithErrorCheck option
  contrib/aws/aws-sdk-go/aws/aws.go
  contrib/aws/aws-sdk-go/aws/aws_test.go
  contrib/aws/aws-sdk-go/aws/option.go
Labels: apm:ecosystem
