Repository DataDog/dd-trace-go, pull requests merged in 2023-08, with the labels that each got.

#2101 tracer: add test for logging 128-bit trace ids when upper bits are empty
  ddtrace/tracer/span_test.go
Labels: tracer, otel

#2171 go.mod: update dependencies to latest
  go.mod
  go.sum
Labels: apm:ecosystem, apm:core

#2142 contrib/IBM/sarama: adds trace for IBM/sarama
  contrib/IBM/sarama.v1/example_test.go
  contrib/IBM/sarama.v1/headers.go
  contrib/IBM/sarama.v1/option.go
  contrib/IBM/sarama.v1/sarama.go
  contrib/IBM/sarama.v1/sarama_test.go
  ddtrace/tracer/option.go
  ddtrace/tracer/option_test.go
  go.mod
  go.sum
Labels: apm:ecosystem

#2188 ddtrace/tracer: add abandoned spans debugger
  ddtrace/tracer/abandonedspans.go
  ddtrace/tracer/abandonedspans_test.go
  ddtrace/tracer/option.go
  ddtrace/tracer/option_test.go
  ddtrace/tracer/span.go
  ddtrace/tracer/tracer.go
Labels: mergequeue-status: error
