Repository DataDog/dd-trace-go, pull requests merged in 2023-07, with the labels that each got.

#2088 contrib/emicklei/go-restful/v3: add integration for newest version
  contrib/emicklei/go-restful/v3/example_test.go
  contrib/emicklei/go-restful/v3/option.go
  contrib/emicklei/go-restful/v3/restful.go
  contrib/emicklei/go-restful/v3/restful_test.go
  go.mod
  go.sum
Labels: apm:ecosystem

#1992 appsec: always tag request and response headers (#1989)
  contrib/emicklei/go-restful/restful_test.go
  contrib/google.golang.org/grpc/appsec.go
  internal/appsec/_testlib/mockspan.go
  internal/appsec/_testlib/require.go
  internal/appsec/dyngo/instrumentation/grpcsec/tags.go
  internal/appsec/dyngo/instrumentation/grpcsec/tags_test.go
  internal/appsec/dyngo/instrumentation/httpsec/http.go
  internal/appsec/dyngo/instrumentation/httpsec/tags.go
  internal/appsec/dyngo/instrumentation/httpsec/tags_test.go
Labels: appsec

#2130 internal: Improve the Iter performance of LockMap on empty maps
  internal/utils.go
  internal/utils_test.go
Labels: no-changelog, apm:core

#2138 contrib/{internal/httptrace, net/http}: fix memory leak and request closure
  contrib/internal/httptrace/httptrace.go
  contrib/net/http/http.go
Labels: apm:core

#2131 github: better initial generated notes with release.yml
  .github/release.yml
Labels: no-changelog

#2126 contrib/segmentio/kafka.go.v0: only log on inject error
  contrib/segmentio/kafka.go.v0/kafka.go
Labels: apm:ecosystem
