Repository DataDog/dd-trace-go, pull requests merged in 2024-12, with the labels that each got.

#2983 Add logic to access strings used by remote config bpf probe
  ddtrace/tracer/remote_config.go
Labels: no-changelog

#2936 internal: add workflow to update outdated integrations
  .github/workflows/apps/latest_major_version.go
  .github/workflows/outdated-integrations.yml
  integration_go.mod
Labels: dev/tooling

#2948 Adding Span Link support for compound header tag extractions with conflicting trace IDs
  contrib/IBM/sarama.v1/sarama.go
  contrib/Shopify/sarama/sarama.go
  contrib/cloud.google.com/go/pubsub.v1/internal/tracing/tracing.go
  contrib/confluentinc/confluent-kafka-go/internal/tracing/consumer.go
  contrib/confluentinc/confluent-kafka-go/internal/tracing/producer.go
  contrib/gofiber/fiber.v2/fiber.go
  contrib/google.golang.org/grpc/grpc.go
  contrib/internal/httptrace/httptrace.go
  contrib/segmentio/kafka.go.v0/internal/tracing/tracing.go
  contrib/twitchtv/twirp/twirp.go
  contrib/valyala/fasthttp.v1/fasthttp.go
  ddtrace/tracer/civisibility_tslv_msgp.go
  ddtrace/tracer/span.go
  ddtrace/tracer/span_msgp.go
  ddtrace/tracer/textmap.go
  ddtrace/tracer/textmap_test.go
  ddtrace/tracer/writer_test.go
Labels: apm:ecosystem, do-not-merge/WIP

#3010 contrib/net/http: Make DD_TRACE_HTTP_CLIENT_TAG_QUERY_STRING false by default
  contrib/google.golang.org/api/api_test.go
  contrib/net/http/option.go
  contrib/net/http/roundtripper_test.go
Labels: apm:ecosystem

#3020 [v2] contrib/net/http: Make DD_TRACE_HTTP_CLIENT_TAG_QUERY_STRING false by default
  contrib/google.golang.org/api/api_test.go
  contrib/net/http/option.go
  contrib/net/http/roundtripper_test.go
Labels: apm:ecosystem

#3008 internal: add workflow to check for outdated integrations
  .github/workflows/apps/latest_major_version.go
  .github/workflows/outdated-integrations.yml
  integration_go.mod
Labels: dev/tooling

#3018 contrib/log/slog: test with slogtest
  contrib/log/slog/slog_test.go
Labels: apm:ecosystem

#3022 chore: update main version to 1.72.0-dev
  internal/version/version.go
Labels: mergequeue-status: error

#3006 ddtrace/tracer: initialize runtimeMetricsV2 with statsd "direct" client
  contrib/database/sql/option_test.go
  ddtrace/mocktracer/mocktracer.go
  ddtrace/tracer/option.go
  ddtrace/tracer/stats.go
  ddtrace/tracer/stats_test.go
  ddtrace/tracer/textmap_test.go
  ddtrace/tracer/tracer_test.go
  go.mod
  go.sum
  internal/apps/go.mod
  internal/apps/go.sum
  internal/datastreams/processor_test.go
  internal/exectracetest/go.mod
  internal/exectracetest/go.sum
  internal/statsd.go
  internal/statsdtest/statsdtest.go
Labels: apm:ecosystem

#2895 contrib/envoyproxy: envoy external processing support
  contrib/envoyproxy/go-control-plane/envoy.go
  contrib/envoyproxy/go-control-plane/envoy_test.go
  contrib/envoyproxy/go-control-plane/example_test.go
  contrib/envoyproxy/go-control-plane/fakehttp.go
  contrib/internal/httptrace/response_writer.go
  go.mod
  go.sum
  internal/appsec/testdata/user_rules.json
Labels: apm:ecosystem, appsec

#3044 appsec: stop storing span tags, directly call span.SetTag
  contrib/99designs/gqlgen/tracer.go
  contrib/google.golang.org/grpc/appsec.go
  contrib/graph-gophers/graphql-go/graphql.go
  contrib/graphql-go/graphql/graphql.go
  internal/appsec/emitter/graphqlsec/request.go
  internal/appsec/emitter/grpcsec/grpc.go
  internal/appsec/emitter/httpsec/http.go
  internal/appsec/emitter/trace/service_entry_span.go
  internal/appsec/emitter/waf/context.go
Labels: apm:ecosystem

#3033 ddtrace/tracer: Tracing as transport-only mode (APPSEC_STANDALONE)
  .github/workflows/system-tests.yml
  contrib/net/http/roundtripper.go
  ddtrace/tracer/log.go
  ddtrace/tracer/log_test.go
  ddtrace/tracer/option.go
  ddtrace/tracer/rules_sampler.go
  ddtrace/tracer/sampler_test.go
  ddtrace/tracer/span.go
  ddtrace/tracer/tracer.go
  ddtrace/tracer/transport.go
  internal/appsec/emitter/waf/context.go
  internal/appsec/emitter/waf/run.go
  internal/appsec/listener/grpcsec/grpc_test.go
  internal/appsec/listener/httpsec/request_test.go
  internal/appsec/listener/waf/tags.go
  internal/appsec/listener/waf/waf.go
  internal/meta_internal_types.go
Labels: apm:ecosystem, appsec

#3049 fix: improving test logic for TestStreamSendsErrorCode to avoid flakiness
  contrib/google.golang.org/grpc/grpc_test.go
Labels: apm:ecosystem
