Repository DataDog/dd-trace-go, pull requests merged in 2024-07, with the labels that each got.

#2765 contrib: add log/slog instrumentation
  contrib/log/slog/example_test.go
  contrib/log/slog/slog.go
  contrib/log/slog/slog_test.go
  contrib/sirupsen/logrus/logrus.go
  ddtrace/ext/log_key.go
  ddtrace/tracer/option.go
  ddtrace/tracer/option_test.go
Labels: apm:ecosystem

#2720 ddtrace/tracer: move execution tracer test to exectracetest
  ddtrace/tracer/exec_tracer_test.go
  internal/apps/go.sum
  internal/exectracetest/exectrace_test.go
  internal/exectracetest/go.sum
Labels: no-changelog, stale

#2752 [contrib/gocql] adding support for MapScanCAS in gocql (cassandra)
  contrib/gocql/gocql/gocql.go
Labels: apm:ecosystem

#2775 contrib/net/http: implement rwUnwrapper
  contrib/net/http/make_responsewriter.go
  contrib/net/http/trace.go
  contrib/net/http/trace_gen.go
  contrib/net/http/trace_test.go
Labels: apm:ecosystem

#2577 [contrib/gocql] reporting both cluster and datacenter
  .github/workflows/unit-integration-tests.yml
  contrib/gocql/gocql/gocql.go
  contrib/gocql/gocql/gocql_test.go
  contrib/gocql/gocql/option.go
  ddtrace/ext/db.go
  docker-compose.yaml
  go.mod
Labels: apm:ecosystem

#2722 contrib/jackc/pgx.v5: acquire release
  .github/workflows/appsec.yml
  contrib/jackc/pgx.v5/option.go
  contrib/jackc/pgx.v5/pgx_tracer.go
  contrib/jackc/pgx.v5/pgx_tracer_test.go
  contrib/jackc/pgx.v5/pgxpool_test.go
  go.mod
  go.sum
Labels: stale

#2776 internal/appsec: refactor simple WAF run operations
  .gitlab-ci.yml
  internal/appsec/listener/graphqlsec/graphql.go
  internal/appsec/listener/grpcsec/grpc.go
  internal/appsec/listener/httpsec/http.go
  internal/appsec/listener/httpsec/roundtripper.go
  internal/appsec/listener/sharedsec/shared.go
  internal/appsec/listener/sqlsec/sql.go
Labels: appsec

#2761 ddtrace/tracer: setup GLS-stored context
  contrib/99designs/gqlgen/tracer.go
  contrib/graph-gophers/graphql-go/graphql.go
  contrib/graphql-go/graphql/graphql.go
  ddtrace/tracer/context.go
  ddtrace/tracer/span.go
  internal/appsec/dyngo/operation.go
  internal/appsec/emitter/graphqlsec/context.go
  internal/appsec/emitter/graphqlsec/execution.go
  internal/appsec/emitter/graphqlsec/request.go
  internal/appsec/emitter/graphqlsec/resolve.go
  internal/appsec/emitter/grpcsec/grpc.go
  internal/appsec/emitter/httpsec/http.go
  internal/appsec/emitter/httpsec/roundtripper.go
  internal/appsec/emitter/sharedsec/shared.go
  internal/appsec/emitter/sqlsec/sql.go
  internal/appsec/listener/listener.go
  internal/orchestrion/context.go
  internal/orchestrion/context_stack.go
  internal/orchestrion/context_test.go
  internal/orchestrion/gls.go
  internal/orchestrion/orchestrion.go
  internal/trace_context.go
Labels: apm:ecosystem, appsec

#2782 upgrade go-libddwaf & appsec-internal-go and remove occurences of go 1.20
  .gitlab/macrobenchmarks.yml
  contrib/database/sql/exec_trace_test.go
  ddtrace/opentelemetry/otel_test.go
  go.mod
  go.sum
  internal/apps/go.mod
  internal/apps/go.sum
  internal/exectracetest/exectrace_go120.go
  internal/exectracetest/exectrace_test.go
  internal/exectracetest/go.mod
  internal/exectracetest/go.sum
  profiler/go_lt_1_21.go
  profiler/pgo_test.go
Labels: apm:ecosystem, ci, dependencies

#2744 tracer: allow x-datadog headers to pass as header tags
  contrib/emicklei/go-restful.v3/restful_test.go
  contrib/emicklei/go-restful/restful_test.go
  contrib/gin-gonic/gin/gintrace_test.go
  contrib/go-chi/chi.v5/chi_test.go
  contrib/go-chi/chi/chi_test.go
  contrib/gorilla/mux/mux_test.go
  contrib/internal/httptrace/httptrace_test.go
  contrib/julienschmidt/httprouter/httprouter_test.go
  contrib/labstack/echo.v4/echotrace_test.go
  contrib/labstack/echo/echotrace_test.go
  contrib/net/http/http_test.go
  contrib/urfave/negroni/negroni_test.go
  ddtrace/tracer/option.go
  internal/normalizer/normalizer.go
  internal/normalizer/normalizer_test.go
Labels: apm:ecosystem

#2779 v2: contrib/README: add versioning and deprecation policies for contribs
  CONTRIBUTING.md
  contrib/README.md
Labels: apm:ecosystem

#2787 ddtrace/mocktracer: fix SetUser & WithUserMetadata
  ddtrace/mocktracer/mockspan.go
  ddtrace/mocktracer/mocktracer_test.go
Labels: bug, apm:core

#2789 contrib/database/sql: remove broken execution trace tests
  contrib/database/sql/exec_trace_test.go
  go.mod
  go.sum
Labels: apm:ecosystem, no-changelog

#2790 internal/exectracetest: port database/sql test to the new parser
  contrib/database/sql/internal/mockdriver.go
  internal/exectracetest/go.mod
  internal/exectracetest/go.sum
  internal/exectracetest/sql_test.go
Labels: apm:ecosystem, no-changelog

#2793 Add instruction how to update Go version for macrobenchmarks
  .gitlab/macrobenchmarks.yml
Labels: ci

#2788 contrib/IBM/sarama.v1: add DSM support
  contrib/IBM/sarama.v1/option.go
  contrib/IBM/sarama.v1/option_test.go
  contrib/IBM/sarama.v1/sarama.go
  contrib/IBM/sarama.v1/sarama_test.go
  contrib/Shopify/sarama/sarama.go
  contrib/Shopify/sarama/sarama_test.go
Labels: apm:ecosystem
