Repository DataDog/dd-trace-go, pull requests merged in 2024-03, with the labels that each got.

#2589 contrib/google.golang.org/grpc: security rule passlist support
  contrib/google.golang.org/grpc/appsec.go
  contrib/google.golang.org/grpc/appsec_test.go
  contrib/google.golang.org/grpc/server.go
  internal/appsec/emitter/grpcsec/types/types.go
  internal/appsec/listener/grpcsec/grpc.go
  internal/appsec/testdata/passlist.json
Labels: apm:ecosystem, appsec

#2587 ddtrace/tracer: go tracer tests lint.
  ddtrace/tracer/abandonedspans_test.go
  ddtrace/tracer/context_test.go
  ddtrace/tracer/sampler_test.go
  ddtrace/tracer/span_test.go
  ddtrace/tracer/spancontext_test.go
  ddtrace/tracer/sqlcomment_test.go
  ddtrace/tracer/textmap_test.go
  ddtrace/tracer/tracer_test.go
  ddtrace/tracer/writer_test.go
Labels: mergequeue-status: removed

#2583 contrib/gofiber/fiber.v2: add possibility to exclude spans generation for specific requests
  contrib/gofiber/fiber.v2/fiber.go
  contrib/gofiber/fiber.v2/fiber_test.go
  contrib/gofiber/fiber.v2/option.go
Labels: apm:ecosystem

#2594 contrib/database/sql: temporarily disable DB stats feature
  contrib/database/sql/example_test.go
  contrib/database/sql/option.go
  contrib/database/sql/option_test.go
  contrib/database/sql/sql_test.go
Labels: apm:ecosystem

#2602 ci: set a large enough appsec timeout value
  .github/workflows/smoke-tests.yml
Labels: ci

#2604 appsec: handle bad redirect action parameters
  internal/appsec/emitter/sharedsec/actions.go
  internal/appsec/emitter/sharedsec/actions_test.go
Labels: appsec

#2619 contrib/net/http: harmonize benchmarks for v2
  contrib/net/http/http_test.go
  contrib/net/http/trace_test.go
  ddtrace/tracer/tracer_test.go
Labels: apm:ecosystem

#2621 chore(test): fixed order of expected and actual values in testify.Ass…
  contrib/google.golang.org/grpc/grpc_test.go
Labels: apm:ecosystem

#2630 Add runtime ID to Dynamic Instrumentation's remote config callback
  ddtrace/tracer/remote_config.go
Labels: team:apm-go

#2629 contrib/database/sql: implementation of DB Stats feature with unique statsd client
  contrib/database/sql/metrics.go
  contrib/database/sql/option.go
  contrib/database/sql/option_test.go
  contrib/database/sql/sql.go
  contrib/database/sql/sql_test.go
  ddtrace/tracer/option.go
  ddtrace/tracer/option_test.go
  ddtrace/tracer/tracer.go
  ddtrace/tracer/tracer_test.go
  internal/globalconfig/globalconfig.go
  internal/globalconfig/globalconfig_test.go
  internal/statsd.go
  internal/statsd_test.go
Labels: apm:ecosystem
