Repository DataDog/dd-trace-go, pull requests merged in 2024-04, with the labels that each got.

#2566 ddtrace: tracer: support for meta_struct field in span
  ddtrace/tracer/meta_struct.go
  ddtrace/tracer/meta_struct_test.go
  ddtrace/tracer/span.go
  ddtrace/tracer/span_msgp.go
  ddtrace/tracer/span_test.go
  ddtrace/tracer/transport_test.go
  ddtrace/tracer/writer.go
  ddtrace/tracer/writer_test.go
  internal/meta_struct.go
Labels: enhancement, core, appsec, tracer

#2637 appsec: collect edge waf headers
  internal/appsec/trace/httptrace/http.go
  internal/appsec/trace/httptrace/http_test.go
Labels: appsec

#2634 appsec: allow enabling sca from configuration
  internal/appsec/appsec.go
  internal/appsec/config/config.go
  internal/appsec/config/config_test.go
  internal/telemetry/client.go
  internal/telemetry/client_test.go
  internal/telemetry/telemetry.go
  internal/telemetry/telemetry_test.go
  internal/telemetry/telemetrytest/telemetrytest.go
Labels: appsec

#2635 contrib/database/sql: use tracer-level tags on contrib's statsd.Client
  contrib/database/sql/metrics.go
  contrib/database/sql/metrics_test.go
  contrib/labstack/echo/echotrace_test.go
  ddtrace/tracer/option.go
  ddtrace/tracer/option_test.go
  internal/globalconfig/globalconfig.go
Labels: apm:ecosystem

#2625 contrib/segmentio/kafka.go.v0: add DSM support
  contrib/segmentio/kafka.go.v0/kafka.go
  contrib/segmentio/kafka.go.v0/kafka_test.go
  contrib/segmentio/kafka.go.v0/option.go
  contrib/segmentio/kafka.go.v0/option_test.go
Labels: apm:ecosystem, mergequeue-status: removed

#2640 [contrib/chi.v5] AppSec handler options
  contrib/gin-gonic/gin/appsec.go
  contrib/go-chi/chi.v5/appsec.go
  contrib/go-chi/chi.v5/chi.go
  contrib/go-chi/chi.v5/option.go
  contrib/go-chi/chi/appsec.go
  contrib/labstack/echo.v4/appsec.go
  contrib/net/http/trace.go
  internal/appsec/emitter/httpsec/config.go
  internal/appsec/emitter/httpsec/http.go
Labels: apm:ecosystem, mergequeue-status: waiting

#2653 version: v1.64.0-dev
  internal/version/version.go
Labels: no-changelog

#2657 workflows: increase timeout of WAF time budget in contrib CI tests
  .github/workflows/multios-unit-tests.yml
  .github/workflows/unit-integration-tests.yml
Labels: ci

#2660 ci(smoke-tests): add go mod tidy job
  .github/workflows/smoke-tests.yml
  internal/apps/go.mod
  internal/apps/go.sum
Labels: ci

#2569 internal: add stacktrace package
  .gitlab-ci.yml
  go.mod
  internal/stacktrace/event.go
  internal/stacktrace/event_msgp.go
  internal/stacktrace/event_test.go
  internal/stacktrace/stacktrace.go
  internal/stacktrace/stacktrace_msgp.go
  internal/stacktrace/stacktrace_test.go
Labels: appsec

#2669 docs: fix dbStats example in contrib/database/sql
  contrib/database/sql/example_test.go
Labels: apm:ecosystem

#2579 ddtrace/tracer: encode/decode reparent ID from tracestate
  ddtrace/opentelemetry/tracer_test.go
  ddtrace/tracer/span.go
  ddtrace/tracer/spancontext.go
  ddtrace/tracer/textmap.go
  ddtrace/tracer/textmap_test.go
  ddtrace/tracer/tracer.go
Labels: stale

#2672 internal: Fixing `_dd.p.dm` decision maker collision on number 10.
  internal/samplernames/samplernames.go
Labels: team:apm-go
