Repository DataDog/dd-trace-go, pull requests merged in 2024-10, with the labels that each got.

#2872 contrib/grpc: attempt to fix flaky tests
  contrib/google.golang.org/grpc/appsec_test.go
  contrib/google.golang.org/grpc/grpc_test.go
Labels: apm:ecosystem, mergequeue-status: in_progress

#2873 Fix and Feature: standardize config behavior across tracing libs
  contrib/internal/httptrace/config.go
  contrib/internal/httptrace/httptrace.go
  contrib/internal/httptrace/httptrace_test.go
  contrib/net/http/http_test.go
  contrib/net/http/option.go
  contrib/net/http/roundtripper.go
  contrib/net/http/roundtripper_test.go
  ddtrace/tracer/rules_sampler.go
  ddtrace/tracer/telemetry.go
  internal/appsec/listener/httpsec/request.go
Labels: apm:ecosystem

#2909 v2: create godoc for contribs
  README.md
  contrib/README.md
  contrib/contrib.go
  ddtrace/tracer/doc.go
Labels: apm:ecosystem, mergequeue-status: in_progress

#2906 v2: remove sampling priority
  appsec/appsec.go
  contrib/dimfeld/httptreemux.v5/example_test.go
  contrib/gorilla/mux/mux_test.go
  contrib/julienschmidt/httprouter/example_test.go
  ddtrace/ext/tags.go
  ddtrace/mocktracer/mocktracer_test.go
  ddtrace/tracer/span.go
  ddtrace/tracer/span_test.go
  ddtrace/tracer/spancontext_test.go
  ddtrace/tracer/sqlcomment_test.go
  ddtrace/tracer/textmap.go
  ddtrace/tracer/textmap_test.go
  ddtrace/tracer/tracer_test.go
Labels: apm:ecosystem

#2885 contrib/segmentio/kafka.go.v0: refactor tracing code
  .github/workflows/unit-integration-tests.yml
  contrib/cloud.google.com/go/pubsub.v1/internal/tracing/tracing.go
  contrib/confluentinc/confluent-kafka-go/kafka.v2/kafka_test.go
  contrib/confluentinc/confluent-kafka-go/kafka/kafka_test.go
  contrib/segmentio/kafka.go.v0/example_test.go
  contrib/segmentio/kafka.go.v0/headers.go
  contrib/segmentio/kafka.go.v0/internal/tracing/dsm.go
  contrib/segmentio/kafka.go.v0/internal/tracing/message_carrier.go
  contrib/segmentio/kafka.go.v0/internal/tracing/tracer.go
  contrib/segmentio/kafka.go.v0/internal/tracing/tracer_test.go
  contrib/segmentio/kafka.go.v0/internal/tracing/tracing.go
  contrib/segmentio/kafka.go.v0/internal/tracing/types.go
  contrib/segmentio/kafka.go.v0/kafka.go
  contrib/segmentio/kafka.go.v0/kafka_test.go
  contrib/segmentio/kafka.go.v0/local_testing.yaml
  contrib/segmentio/kafka.go.v0/option.go
  contrib/segmentio/kafka.go.v0/tracing.go
  docker-compose.yaml
Labels: apm:ecosystem

#2929 contrib/slog: clone record before calling Add
  contrib/log/slog/slog.go
  contrib/log/slog/slog_test.go
Labels: apm:ecosystem

#2932 contrib/jackc/pgx.v5: wrap previous tracer
  contrib/jackc/pgx.v5/pgx.go
  contrib/jackc/pgx.v5/pgx_tracer.go
  contrib/jackc/pgx.v5/pgx_tracer_test.go
  contrib/jackc/pgx.v5/pgxpool.go
Labels: apm:ecosystem

#2921 contrib/net/http: refactor tracing
  contrib/internal/httptrace/before_handle.go
  contrib/internal/httptrace/make_responsewriter.go
  contrib/internal/httptrace/response_writer.go
  contrib/internal/httptrace/response_writer_test.go
  contrib/internal/httptrace/trace_gen.go
  contrib/julienschmidt/httprouter/httprouter.go
  contrib/julienschmidt/httprouter/internal/tracing/config.go
  contrib/julienschmidt/httprouter/internal/tracing/tracing.go
  contrib/julienschmidt/httprouter/option.go
  contrib/net/http/trace.go
  contrib/net/http/trace_test.go
  internal/appsec/emitter/httpsec/http.go
Labels: apm:ecosystem

#2907 contrib/confluentinc/confluent-kafka-go: split tracing code
  contrib/confluentinc/confluent-kafka-go/internal/tracing/consumer.go
  contrib/confluentinc/confluent-kafka-go/internal/tracing/dsm.go
  contrib/confluentinc/confluent-kafka-go/internal/tracing/kafka_tracer.go
  contrib/confluentinc/confluent-kafka-go/internal/tracing/kafka_tracer_test.go
  contrib/confluentinc/confluent-kafka-go/internal/tracing/message_carrier.go
  contrib/confluentinc/confluent-kafka-go/internal/tracing/producer.go
  contrib/confluentinc/confluent-kafka-go/internal/tracing/tracing.go
  contrib/confluentinc/confluent-kafka-go/internal/tracing/types.go
  contrib/confluentinc/confluent-kafka-go/kafka.v2/headers.go
  contrib/confluentinc/confluent-kafka-go/kafka.v2/kafka.go
  contrib/confluentinc/confluent-kafka-go/kafka.v2/kafka_test.go
  contrib/confluentinc/confluent-kafka-go/kafka.v2/option.go
  contrib/confluentinc/confluent-kafka-go/kafka.v2/tracing.go
  contrib/confluentinc/confluent-kafka-go/kafka/headers.go
  contrib/confluentinc/confluent-kafka-go/kafka/kafka.go
  contrib/confluentinc/confluent-kafka-go/kafka/kafka_test.go
  contrib/confluentinc/confluent-kafka-go/kafka/option.go
  contrib/confluentinc/confluent-kafka-go/kafka/option_test.go
  contrib/confluentinc/confluent-kafka-go/kafka/tracing.go
  ddtrace/tracer/option_test.go
Labels: apm:ecosystem

#2938 [godfathering] contrib/dimfeld/httptreemux.v5: failing tests for path variable replacement
  contrib/dimfeld/httptreemux.v5/httptreemux.go
  contrib/dimfeld/httptreemux.v5/httptreemux_test.go
Labels: apm:ecosystem

#2917 [serverless] Inject trace context into SQS/SNS/EventBridge
  contrib/aws/aws-sdk-go-v2/aws/aws.go
  contrib/aws/aws-sdk-go-v2/aws/aws_test.go
  contrib/aws/internal/eventbridge/eventbridge.go
  contrib/aws/internal/eventbridge/eventbridge_test.go
  contrib/aws/internal/sns/sns.go
  contrib/aws/internal/sns/sns_test.go
  contrib/aws/internal/sqs/sqs.go
  contrib/aws/internal/sqs/sqs_test.go
Labels: apm:ecosystem, serverless

#2857 contrib/log/slog: fix WithAttrs and WithGroup implementation
  contrib/log/slog/slog.go
  contrib/log/slog/slog_test.go
Labels: apm:ecosystem

#2840 profiler: add enable flag to control profiler activation
  profiler/options.go
  profiler/options_test.go
  profiler/profiler.go
  profiler/profiler_test.go
  profiler/telemetry.go
Labels: profiler

#2942 [SVLS-5560] Inject DD trace context into AWS Step Functions input
  contrib/aws/aws-sdk-go-v2/aws/aws.go
  contrib/aws/internal/sfn/sfn.go
  contrib/aws/internal/sfn/sfn_test.go
Labels: apm:ecosystem

#2914 v2: finalize migration tool for v2
  tools/v2check/README.md
  tools/v2check/_stage/traceidstring/traceidstring.go
  tools/v2check/_stage/traceidstring/traceidstring.go.golden
  tools/v2check/_stage/withservicename/withservicename.go
  tools/v2check/_stage/withservicename/withservicename.go.golden
  tools/v2check/main.go
  tools/v2check/v2check/known_change.go
  tools/v2check/v2check/probe.go
  tools/v2check/v2check/v2check_test.go
Labels: apm:ecosystem
