Repository DataDog/dd-trace-go, pull requests merged in 2024-11, with the labels that each got.

#2962 contrib/valyala/fasthttp.v1: fix memory leak of spanOpts
  contrib/valyala/fasthttp.v1/fasthttp.go
Labels: apm:ecosystem

#2926 profiler: add DD_PROFILING_FLUSH_ON_EXIT to upload current profiles before exiting
  profiler/options.go
  profiler/profiler.go
  profiler/profiler_test.go
  profiler/telemetry.go
  profiler/upload.go
Labels: profiler

#2960 contrib/go-chi: Apply DD_TRACE_HTTP_SERVER_ERROR_STATUSES
  contrib/go-chi/chi.v5/chi_test.go
  contrib/go-chi/chi.v5/option.go
  contrib/go-chi/chi/chi_test.go
  contrib/go-chi/chi/option.go
  contrib/internal/httptrace/config.go
  contrib/internal/httptrace/httptrace_test.go
Labels: apm:ecosystem

#2772 ddtrace/tracer: runtime metrics v2 (exclude from release notes)
  ddtrace/tracer/log.go
  ddtrace/tracer/log_test.go
  ddtrace/tracer/option.go
  ddtrace/tracer/slog.go
  ddtrace/tracer/slog_test.go
  ddtrace/tracer/telemetry.go
  ddtrace/tracer/tracer.go
  go.mod
  go.sum
  internal/apps/apps.go
  internal/apps/go.mod
  internal/apps/go.sum
  internal/exectracetest/go.mod
  internal/exectracetest/go.sum
  internal/log/log.go
  internal/statsd.go
  internal/statsdtest/statsdtest.go
Labels: no-changelog

#2977 Add APPSEC_RUNTIME_ACTIVATION scenario in system-tests
  .github/workflows/system-tests.yml
Labels: mergequeue-status: in_progress

#2989 appsec: never start a new WAF Context when one is in context
  internal/appsec/dyngo/operation.go
  internal/appsec/dyngo/operation_test.go
  internal/appsec/emitter/graphqlsec/request.go
  internal/appsec/emitter/grpcsec/grpc.go
  internal/appsec/emitter/httpsec/http.go
Labels: appsec
