Repository DataDog/dd-trace-go, pull requests merged in 2024-06, with the labels that each got.

#2707 appsec: support for SSRF Exploit Prevention
  appsec/events/block.go
  contrib/google.golang.org/grpc/appsec.go
  contrib/labstack/echo.v4/appsec.go
  contrib/net/http/roundtripper.go
  contrib/net/http/roundtripper_test.go
  go.mod
  go.sum
  internal/apps/go.mod
  internal/apps/go.sum
  internal/appsec/appsec.go
  internal/appsec/config/config.go
  internal/appsec/emitter/grpcsec/types/types.go
  internal/appsec/emitter/httpsec/http.go
  internal/appsec/emitter/httpsec/roundtripper.go
  internal/appsec/emitter/httpsec/types/types.go
  internal/appsec/emitter/sharedsec/actions.go
  internal/appsec/emitter/sharedsec/shared.go
  internal/appsec/listener/graphqlsec/graphql.go
  internal/appsec/listener/grpcsec/grpc.go
  internal/appsec/listener/httpsec/http.go
  internal/appsec/listener/httpsec/roundtripper.go
  internal/appsec/listener/sharedsec/shared.go
  internal/appsec/remoteconfig.go
  internal/appsec/testdata/rasp.json
  internal/appsec/waf_test.go
  internal/exectracetest/go.mod
  internal/exectracetest/go.sum
  internal/remoteconfig/remoteconfig.go
  internal/stacktrace/event.go
  internal/stacktrace/event_test.go
Labels: apm:ecosystem

#2723 appsec/grpc: fix rpc message blocking
  contrib/google.golang.org/grpc/appsec.go
  contrib/google.golang.org/grpc/appsec_test.go
  internal/appsec/emitter/sharedsec/actions.go
  internal/appsec/listener/grpcsec/grpc.go
Labels: apm:ecosystem, appsec

#2733 upgrade go-libddwaf: v3.2.0 -> v3.2.1
  go.mod
  go.sum
  internal/apps/go.mod
  internal/apps/go.sum
  internal/exectracetest/go.mod
  internal/exectracetest/go.sum
Labels: appsec

#2746 appsec: fix IsSecurityError
  appsec/events/block.go
  contrib/net/http/roundtripper_test.go
Labels: bug, apm:ecosystem, appsec

#2754 workflows: enable APPSEC_RASP system-tests scenario
  .github/workflows/system-tests.yml
Labels: appsec, ci
