Repository DataDog/dd-trace-go, pull requests merged in 2024-01, with the labels that each got.

#2471 tools/v2check: basic implementation
  tools/v2check/_stage/ddtrace_simple.go
  tools/v2check/_stage/go.mod
  tools/v2check/_stage/go.sum
  tools/v2check/go.mod
  tools/v2check/go.sum
  tools/v2check/known_change.go
  tools/v2check/main.go
  tools/v2check/v2check.go
  tools/v2check/v2check_test.go
Labels: v2.0, no-changelog

#2474 contrib: set set span.kind and component in httptrace.TraceAndServe
  v2/contrib/net/http/trace.go
  v2/contrib/net/http/trace_test.go
Labels: apm:ecosystem

#2492 ddtracer/tracer: update TestStartupLog/errors & TestLogSamplingRules to new sampling rules implementation in v2
  ddtrace/tracer/log_test.go
Labels: v2.0

#2434 readme.md: update the appsec intro
  README.md
Labels: stale

#2498 ddtrace/tracer: enable nil-object pattern for spans
  ddtrace/tracer/context.go
  ddtrace/tracer/rules_sampler.go
  ddtrace/tracer/span.go
  ddtrace/tracer/span_test.go
  ddtrace/tracer/spancontext.go
  ddtrace/tracer/spancontext_test.go
  ddtrace/tracer/tracer.go
Labels: v2.0

#2517 internal/telemetry: remove DetectLibDl
  ddtrace/tracer/telemetry.go
  internal/appsec/telemetry.go
  internal/osinfo/osinfo.go
  internal/osinfo/osinfo_test.go
Labels: mergequeue-status: removed

#2511 [data streams] Track high watermark offsets
  contrib/confluentinc/confluent-kafka-go/kafka.v2/kafka.go
  contrib/confluentinc/confluent-kafka-go/kafka.v2/kafka_test.go
  contrib/confluentinc/confluent-kafka-go/kafka/kafka.go
  contrib/confluentinc/confluent-kafka-go/kafka/kafka_test.go
  ddtrace/mocktracer/data_streams.go
  ddtrace/mocktracer/mocktracer.go
  ddtrace/tracer/data_streams.go
  internal/datastreams/processor.go
Labels: apm:ecosystem

#1567 contrib/labstack/echo.v4: add option to ignore errors
  contrib/labstack/echo.v4/echotrace.go
  contrib/labstack/echo.v4/echotrace_test.go
  contrib/labstack/echo.v4/option.go
Labels: apm:ecosystem, proposal/accepted
