Repository DataDog/dd-trace-go, pull requests merged in 2024-02, with the labels that each got.

#2537 ci/appsec: refresher
  .github/workflows/apps/appsec-test-contrib-submodules.sh
  .github/workflows/appsec.yml
Labels: appsec, ci

#2394 dyngo: dynamically register listeners only if they're needed
  contrib/99designs/gqlgen/tracer.go
  contrib/google.golang.org/grpc/appsec.go
  contrib/graph-gophers/graphql-go/graphql.go
  contrib/graphql-go/graphql/graphql.go
  contrib/labstack/echo.v4/appsec.go
  internal/appsec/dyngo/operation.go
  internal/appsec/dyngo/operation_test.go
  internal/appsec/emitter/graphqlsec/execution.go
  internal/appsec/emitter/graphqlsec/init.go
  internal/appsec/emitter/graphqlsec/request.go
  internal/appsec/emitter/graphqlsec/resolve.go
  internal/appsec/emitter/graphqlsec/types/types.go
  internal/appsec/emitter/grpcsec/grpc.go
  internal/appsec/emitter/grpcsec/grpc_test.go
  internal/appsec/emitter/grpcsec/init.go
  internal/appsec/emitter/grpcsec/types/types.go
  internal/appsec/emitter/httpsec/http.go
  internal/appsec/emitter/httpsec/init.go
  internal/appsec/emitter/httpsec/types/types.go
  internal/appsec/emitter/sharedsec/shared.go
  internal/appsec/listener/graphqlsec/graphql.go
  internal/appsec/listener/grpcsec/grpc.go
  internal/appsec/listener/httpsec/http.go
  internal/appsec/listener/listener.go
  internal/appsec/listener/sharedsec/shared.go
  internal/appsec/waf.go
Labels: apm:ecosystem, mergequeue-status: in_progress

#2410 contrib/jackc/pgx.v5: add pgx support
  contrib/jackc/pgx.v5/example_test.go
  contrib/jackc/pgx.v5/option.go
  contrib/jackc/pgx.v5/pgx.go
  contrib/jackc/pgx.v5/pgx_tracer.go
  contrib/jackc/pgx.v5/pgx_tracer_test.go
  contrib/jackc/pgx.v5/pgxpool.go
  contrib/jackc/pgx.v5/pgxpool_test.go
  go.mod
  go.sum
Labels: apm:ecosystem

#2558 [DSM] Close span on produce error in ckgo
  contrib/confluentinc/confluent-kafka-go/kafka.v2/kafka.go
  contrib/confluentinc/confluent-kafka-go/kafka/kafka.go
Labels: apm:ecosystem

#2550 contrib/database/sql: add in ddh, dddb propagation
  README.md
  contrib/database/sql/conn.go
  contrib/database/sql/internal/dsn.go
  contrib/database/sql/propagation_test.go
  ddtrace/tracer/sqlcomment.go
  ddtrace/tracer/sqlcomment_test.go
Labels: apm:ecosystem, mergequeue-status: in_progress

#2541 ci/appsec: smaller matrix and faster jobs
  .github/workflows/apps/appsec-test-contrib-submodules.sh
  .github/workflows/appsec.yml
Labels: appsec, ci

#2568 appsec: remoteconfig: rework ASM_DD config removal
  internal/appsec/config/rules_manager.go
  internal/appsec/remoteconfig.go
  internal/appsec/remoteconfig_test.go
Labels: bug, appsec

#2510 tracer/remote-config: Subscribe to dynamic instrumentation configs via remote config
  ddtrace/tracer/option.go
  ddtrace/tracer/remote_config.go
Labels: team:apm-go

#2584 contrib/google.golang.org/grpc: fix flaky tests by removing arbitrary sleeps
  contrib/google.golang.org/grpc/grpc_test.go
Labels: apm:ecosystem, ci

#2586 ci/appsec: test on debian arm64
  .github/workflows/appsec.yml
Labels: appsec, ci
