Repository DataDog/dd-trace-go, pull requests merged in 2024-09, with the labels that each got.

#2841 internal/appsec: fix missing ResponseHeaderCopier call
  internal/appsec/emitter/httpsec/http.go
Labels: appsec

#2850 all: upgrade minimum supported Go release to 1.22
  .github/workflows/appsec.yml
  .github/workflows/main-branch-tests.yml
  .github/workflows/pull-request.yml
  .github/workflows/smoke-tests.yml
  .github/workflows/unit-integration-tests.yml
  contrib/net/http/http_test.go
  ddtrace/tracer/rand.go
  ddtrace/tracer/rand_go1_22.go
  go.mod
  internal/apps/Dockerfile
  internal/apps/go.mod
  internal/apps/setup-smoke-test/Dockerfile
  internal/appsec/config/rules_manager.go
  internal/exectracetest/go.mod
Labels: apm:ecosystem

#2814 profiler: record Orchestrion, activation information
  profiler/profiler_test.go
  profiler/upload.go
Labels: no-changelog

#2878 appsec: Suspicious Attacker Blocking
  go.mod
  go.sum
  internal/apps/go.mod
  internal/apps/go.sum
  internal/appsec/appsec.go
  internal/appsec/config/config.go
  internal/appsec/config/rules_manager.go
  internal/appsec/listener/httpsec/http.go
  internal/appsec/remoteconfig.go
  internal/appsec/remoteconfig_test.go
  internal/appsec/testdata/sab.json
  internal/appsec/waf_test.go
  internal/exectracetest/go.mod
  internal/exectracetest/go.sum
Labels: appsec, mergequeue-status: error

#2865 profiler: avoid metrics profile log noise when stopping profiling
  profiler/metrics.go
  profiler/metrics_test.go
  profiler/profiler_test.go
Labels: profiler

#2845 ddtrace/tracer: update log msg to accurately count dropped traces
  ddtrace/tracer/spancontext_test.go
  ddtrace/tracer/tracer.go
Labels: mergequeue-status: in_progress

#2886 profiler: suppress errors if the profiler is stopped
  profiler/profile.go
  profiler/profiler.go
Labels: no-changelog

#2792 contrib/99designs/gqlgen/tracer.go: nil check response
  contrib/99designs/gqlgen/tracer.go
  contrib/99designs/gqlgen/tracer_test.go
Labels: apm:ecosystem

#2898 Fix typo in README.md
  README.md
Labels: no-changelog
