Repository DataDog/dd-trace-go, pull requests merged in 2024-05, with the labels that each got.

#2633 [v2] ddtrace/tracer: tidy up Tracer interface
  ddtrace/mocktracer/mocktracer.go
  ddtrace/tracer/globaltracer_test.go
  ddtrace/tracer/noop.go
  ddtrace/tracer/span.go
  ddtrace/tracer/spancontext.go
  ddtrace/tracer/tracer.go
  ddtrace/tracer/tracer_test.go
Labels: stale

#2682 contrib/database/sql: Disable DBStats if statsd client initialization fails
  contrib/database/sql/metrics.go
  contrib/database/sql/option.go
  contrib/database/sql/option_test.go
  contrib/database/sql/sql.go
Labels: apm:ecosystem

#2676 ddtrace/tracer: adding support of tags in remote sampling rules.
  ddtrace/tracer/remote_config.go
  ddtrace/tracer/remote_config_test.go
  ddtrace/tracer/rules_sampler.go
Labels: team:apm-go, mergequeue-status: removed

#2704 ci: use correct path for Windows datadog-ci release
  .github/actions/dd-ci-upload/action.yml
Labels: no-changelog

#2698 go.mod: update github.com/DataDog/sketches-go to v1.4.5
  contrib/google.golang.org/grpc/grpc.go
  go.mod
  go.sum
  internal/apps/go.mod
  internal/apps/go.sum
Labels: apm:ecosystem

#2670 appsec: upgrade go-libddwaf/v3
  .github/workflows/smoke-tests.yml
  contrib/google.golang.org/grpc/appsec.go
  go.mod
  go.sum
  internal/apps/go.mod
  internal/apps/go.sum
  internal/apps/setup-smoke-test/Dockerfile
  internal/appsec/appsec.go
  internal/appsec/appsec_test.go
  internal/appsec/config/rule_test.go
  internal/appsec/config/rules_manager.go
  internal/appsec/emitter/httpsec/http.go
  internal/appsec/emitter/sharedsec/actions.go
  internal/appsec/emitter/sharedsec/actions_test.go
  internal/appsec/listener/graphqlsec/graphql.go
  internal/appsec/listener/grpcsec/grpc.go
  internal/appsec/listener/httpsec/http.go
  internal/appsec/listener/listener.go
  internal/appsec/listener/sharedsec/shared.go
  internal/appsec/listener/sharedsec/shared_test.go
  internal/appsec/remoteconfig_test.go
  internal/appsec/telemetry.go
  internal/appsec/waf.go
  internal/appsec/waf_test.go
  internal/appsec/waf_unit_test.go
Labels: apm:ecosystem, appsec

#2679 contrib/database/sql: allow peer.service to be set explicitly and add into propagated context
  contrib/database/sql/conn.go
  contrib/database/sql/propagation_test.go
  ddtrace/tracer/sqlcomment.go
  ddtrace/tracer/sqlcomment_test.go
Labels: apm:ecosystem

#2623 ddtrace/tracer: support default origin on dynamic config to support Active Tracing telemetry spec
  ddtrace/tracer/dynamic_config.go
  ddtrace/tracer/option.go
  ddtrace/tracer/option_test.go
  ddtrace/tracer/remote_config_test.go
  ddtrace/tracer/telemetry.go
  ddtrace/tracer/telemetry_test.go
  ddtrace/tracer/tracer.go
  internal/appsec/config/config.go
  internal/appsec/config/config_test.go
  internal/appsec/telemetry.go
  internal/telemetry/client.go
  internal/telemetry/message.go
  internal/telemetry/telemetry_test.go
  internal/telemetry/telemetrytest/telemetrytest.go
Labels: team:apm-go

#2716 contrib/net/http: Support go1.22 ServeMux patterns
  contrib/net/http/http.go
  contrib/net/http/http_test.go
Labels: apm:ecosystem

#2702 profiler: remove TestProfilerPassthrough and BenchmarkDoRequest
  profiler/profiler_test.go
  profiler/upload_test.go
Labels: no-changelog

#2706 profiler: remove TestTryUpload
  profiler/profiler_test.go
  profiler/upload_test.go
Labels: no-changelog

#2709 internal/exectracetest: move execution trace testing to separate module
  .github/workflows/unit-integration-tests.yml
  internal/exectracetest/exectrace_go120.go
  internal/exectracetest/exectrace_test.go
  internal/exectracetest/go.mod
  internal/exectracetest/go.sum
Labels: no-changelog

#2708 ddtrace/tracer: only finish execution trace task, restore pprof labels once
  .github/workflows/unit-integration-tests.yml
  ddtrace/tracer/span.go
  internal/exectracetest/exectrace_go120.go
  internal/exectracetest/exectrace_test.go
  internal/exectracetest/go.mod
  internal/exectracetest/go.sum
Labels: tracer
