Repository DataDog/dd-trace-go, pull requests merged in 2025-08, with the labels that each got.

#3830 fix(internal/setup-smoke-test): use JSON arguments for CMD/ENTRYPOINT and change alias in FROM scratch
  .github/workflows/smoke-tests.yml
  internal/setup-smoke-test/Dockerfile
Labels: mergequeue-status: in_progress

#3832 ci: remove commit sha tag from released images and add it as container label
  .github/workflows/docker-build-and-push.yml
  .github/workflows/docker-images-release.yml
  contrib/envoyproxy/go-control-plane/cmd/serviceextensions/Dockerfile
  contrib/k8s.io/gateway-api/cmd/request-mirror/Dockerfile
Labels: apm:ecosystem, mergequeue-status: in_progress

#3833 chore(ci): Improve CI
  .github/actions/setup-go/action.yml
  .github/workflows/generate.yml
  .github/workflows/static-checks.yml
  .github/workflows/unit-integration-tests.yml
  .gitignore
  .pre-commit-config.yaml
  CONTRIBUTING.md
  Makefile
  README.md
  _tools/go.mod
  _tools/go.sum
  _tools/tools.go
  scripts/README.md
  scripts/check_locks.sh
  scripts/ci_test_contrib.sh
  scripts/fix_modules.sh
  scripts/fixmodules/main.go
  scripts/format.sh
  scripts/install_tools.sh
  scripts/lint.sh
  scripts/test.sh
Labels: mergequeue-status: in_progress

#3842 feat(.github/chainguard): add outdated integrations policy for STS migration
  .github/chainguard/self.outdated-integrations.sts.yaml
Labels: mergequeue-status: in_progress

#3843 feat(.github/workflows): Migrate outdated integrations to use STS
  .github/workflows/needs-triage.yml
  .github/workflows/outdated-integrations.yml
Labels: mergequeue-status: in_progress

#3846 docs(MIGRATING.md): Clarify migration tool name in documentation
  MIGRATING.md
Labels: mergequeue-status: in_progress

#3728 fix(contrib/99designs/gqlgen): fix panic on empty response from response handler
  contrib/99designs/gqlgen/internal/testserver/gqlgen.yml
  contrib/99designs/gqlgen/internal/testserver/graph/generated.go
  contrib/99designs/gqlgen/internal/testserver/graph/model/model.go
  contrib/99designs/gqlgen/internal/testserver/graph/schema.graphqls
  contrib/99designs/gqlgen/internal/testserver/graph/schema.resolvers.go
  contrib/99designs/gqlgen/internal/testserver/server.go
  contrib/99designs/gqlgen/tracer.go
  contrib/99designs/gqlgen/tracer_test.go
Labels: mergequeue-status: in_progress

#3847 fix(.github/workflows): Add path normalization function to convert forward slashes to backslashes on Windows runners
  .github/workflows/multios-unit-tests.yml
Labels: mergequeue-status: in_progress

#3826 refactor(ddtrace/tracer): prepare payload.push for supporting v1 trace protocol
  ddtrace/tracer/payload.go
Labels: mergequeue-status: in_progress

#3849 fix(.github/chainguard): Remove event_name field in outdated integrations policy
  .github/chainguard/self.outdated-integrations.sts.yaml
Labels: mergequeue-status: in_progress

#3854 chore: upgrade gofiber/fiber to v2.52.9 to avoid crashes
  contrib/confluentinc/confluent-kafka-go/kafka.v2/go.mod
  contrib/confluentinc/confluent-kafka-go/kafka.v2/go.sum
  contrib/gofiber/fiber.v2/go.mod
  contrib/gofiber/fiber.v2/go.sum
  contrib/valyala/fasthttp/go.mod
  contrib/valyala/fasthttp/go.sum
  go.work.sum
  instrumentation/internal/namingschematest/go.mod
  instrumentation/internal/namingschematest/go.sum
  internal/orchestrion/_integration/go.mod
  internal/orchestrion/_integration/go.sum
  orchestrion/all/go.mod
  orchestrion/all/go.sum
Labels: apm:ecosystem, mergequeue-status: in_progress

#3867 ci: fix docker images releases
  .github/workflows/docker-build-and-push.yml
Labels: mergequeue-status: in_progress

#3862 chore(internal/civisibility): reduce civisibility gotesting tests verbosity
  internal/civisibility/integrations/gotesting/testcontroller_test.go
Labels: mergequeue-status: in_progress

#3865 fix(contrib/net/http): workaround to fix symbol collision in Orchestrion
  contrib/net/http/orchestrion.client.yml
  internal/orchestrion/_integration/net_http/generated_test.go
  internal/orchestrion/_integration/net_http/global_functions.go
Labels: apm:ecosystem, mergequeue-status: in_progress

#3888 chore: prevent smoke tests from failing-fast
  .github/workflows/smoke-tests.yml
Labels: mergequeue-status: in_progress

#3870 fix(scripts): fix fix_modules.sh script
  go.work
  scripts/fix_modules.sh
  scripts/fixmodules/main.go
Labels: mergequeue-status: in_progress

#3897 refactor(internal/appsec): move apisec sampler out of appsec-internal-go
  internal/appsec/apisec/internal/config/const.go
  internal/appsec/apisec/internal/timed/clock.go
  internal/appsec/apisec/internal/timed/lru.go
  internal/appsec/apisec/internal/timed/lru_test.go
  internal/appsec/apisec/internal/timed/table.go
  internal/appsec/apisec/internal/timed/table_test.go
  internal/appsec/apisec/sampler.go
  internal/appsec/apisec/sampler_test.go
  internal/appsec/listener/httpsec/http.go
  internal/appsec/listener/httpsec/request_test.go
  internal/appsec/waf_test.go
Labels: appsec

#3919 chore(.gitlab): align bp-runner.fail-on-breach names to macrobenchmarks
  .gitlab/bp-runner.fail-on-breach.yml
Labels: mergequeue-status: in_progress

#3923 feat(contrib/labstack/echo): analyze parsed request body
  contrib/labstack/echo.v4/appsec.go
  contrib/labstack/echo.v4/appsec_test.go
Labels: apm:ecosystem

#3929 ci: fix PR title validation regexp
  .github/workflows/pull-request-title-validation.yml
Labels: mergequeue-status: in_progress
