Repository DataDog/dd-trace-go, pull requests merged in 2025-01, with the labels that each got.

#3047 contrib/envoyproxy: fix resource name
  contrib/envoyproxy/go-control-plane/envoy.go
  contrib/envoyproxy/go-control-plane/envoy_test.go
Labels: apm:ecosystem

#3041 contrib/IBM/sarama.v1: support for consumer groups
  contrib/IBM/sarama.v1/consumer.go
  contrib/IBM/sarama.v1/consumer_group.go
  contrib/IBM/sarama.v1/consumer_group_test.go
  contrib/IBM/sarama.v1/consumer_test.go
  contrib/IBM/sarama.v1/dispatcher.go
  contrib/IBM/sarama.v1/example_test.go
  contrib/IBM/sarama.v1/producer.go
  contrib/IBM/sarama.v1/producer_test.go
  contrib/IBM/sarama.v1/sarama.go
  contrib/IBM/sarama.v1/sarama_test.go
Labels: apm:ecosystem

#3073 contrib/IBM/sarama.v1: remove commented code
  contrib/IBM/sarama.v1/sarama_test.go
Labels: apm:ecosystem

#3072 [v2] contrib/IBM/sarama: support for consumer groups
  contrib/IBM/sarama/consumer.go
  contrib/IBM/sarama/consumer_group.go
  contrib/IBM/sarama/consumer_group_test.go
  contrib/IBM/sarama/consumer_test.go
  contrib/IBM/sarama/dispatcher.go
  contrib/IBM/sarama/example_test.go
  contrib/IBM/sarama/producer.go
  contrib/IBM/sarama/producer_test.go
  contrib/IBM/sarama/sarama.go
  contrib/IBM/sarama/sarama_test.go
  go.work.sum
Labels: apm:ecosystem

#3012 contrib/http/net: adding integration-level option to configure error codes
  contrib/internal/httptrace/before_handle.go
  contrib/net/http/http.go
  contrib/net/http/option.go
  contrib/net/http/trace_test.go
Labels: apm:ecosystem

#3079 contrib/net/http: support for path params from go 1.22 proposal
  contrib/net/http/get_pattern.go
  contrib/net/http/get_pattern_go122.go
  contrib/net/http/http.go
  contrib/net/http/http_test.go
  contrib/net/http/pattern.go
  contrib/net/http/pattern_test.go
Labels: apm:ecosystem, appsec

#3071 contrib/net/http: Obfuscate query strings on http client spans
  contrib/google.golang.org/api/api_test.go
  contrib/internal/httptrace/config.go
  contrib/internal/httptrace/httptrace.go
  contrib/internal/httptrace/httptrace_test.go
  contrib/net/http/option.go
  contrib/net/http/roundtripper.go
  contrib/net/http/roundtripper_test.go
Labels: apm:ecosystem

#3089 contrib/envoyproxy: fix empty request
  contrib/envoyproxy/go-control-plane/envoy.go
  contrib/envoyproxy/go-control-plane/envoy_test.go
Labels: apm:ecosystem

#3091 fix(staticcheck): Fix trivial go vet issues
  contrib/jackc/pgx.v5/example_test.go
  contrib/labstack/echo.v4/appsec_test.go
  internal/utils_test.go
Labels: apm:ecosystem

#3093 [v2] contrib/IBM/sarama.v1: skip integration test if env variable is not set
  contrib/IBM/sarama/consumer_group_test.go
Labels: apm:ecosystem

#3090 [v2] tools: fix fixmodules script
  contrib/envoyproxy/go-control-plane/go.mod
  contrib/envoyproxy/go-control-plane/go.sum
  contrib/julienschmidt/httprouter/go.mod
  go.mod
  internal/apps/go.mod
  internal/apps/go.sum
  internal/setup-smoke-test/go.mod
  internal/traceprof/traceproftest/go.mod
  internal/traceprof/traceproftest/go.sum
  tools/fixmodules/go.mod
  tools/fixmodules/go.sum
  tools/fixmodules/main.go
Labels: apm:ecosystem

#3098 appsec: meta_struct Security Events
  .github/workflows/system-tests.yml
  ddtrace/tracer/option.go
  ddtrace/tracer/tracer.go
  internal/appsec/config/config.go
  internal/appsec/listener/waf/waf.go
  internal/appsec/waf_test.go
Labels: appsec

#3084 ddtrace/tracer: Support DD_DOGSTATSD_HOST env var
  contrib/net/http/trace_test.go
  ddtrace/tracer/log.go
  ddtrace/tracer/log_test.go
  ddtrace/tracer/option.go
  ddtrace/tracer/option_test.go
Labels: apm:ecosystem

#3105 [v2] fix(contrib/Shopify/sarama): pin Shopify/sarama to v1.38.1
  contrib/Shopify/sarama/go.mod
  contrib/Shopify/sarama/sarama.go
  go.work.sum
Labels: apm:ecosystem

#3104 contrib/IBM/sarama.v1: stop using mockbroker for tests
  contrib/IBM/sarama.v1/consumer_group_test.go
  contrib/IBM/sarama.v1/consumer_test.go
  contrib/IBM/sarama.v1/producer_test.go
  contrib/IBM/sarama.v1/sarama_test.go
Labels: apm:ecosystem

#3107 [v2] fix(contrib/hashicorp/{consul,vault}): pin armon/go-metrics to v0.4.1
  contrib/hashicorp/consul/go.mod
  contrib/hashicorp/consul/go.sum
  contrib/hashicorp/vault/go.mod
Labels: apm:ecosystem

#3070 internal: add supported versions for v2
  .github/workflows/apps/gen_supported_versions_doc.go
  .github/workflows/apps/go.mod
  .github/workflows/apps/go.sum
  .github/workflows/update-supported-versions-doc.yml
  contrib/k8s.io/client-go/kubernetes/kubernetes.go
  contrib/olivere/elastic.v5/elastictrace.go
  contrib/supported_versions.md
  go.work
  go.work.sum
  instrumentation/packages.go
  integration_go.mod
Labels: apm:ecosystem

#3052 contrib/internal/httptrace: add support for inferred proxy spans
  contrib/emicklei/go-restful.v3/restful.go
  contrib/emicklei/go-restful/restful.go
  contrib/gin-gonic/gin/gintrace.go
  contrib/go-chi/chi.v5/chi.go
  contrib/go-chi/chi/chi.go
  contrib/internal/httptrace/before_handle.go
  contrib/internal/httptrace/config.go
  contrib/internal/httptrace/httptrace.go
  contrib/internal/httptrace/httptrace_api_gateway_test.go
  contrib/internal/httptrace/httptrace_test.go
  contrib/internal/httptrace/inferred_proxy.go
  contrib/labstack/echo.v4/echotrace.go
  contrib/labstack/echo/echotrace.go
  contrib/urfave/negroni/negroni.go
Labels: apm:ecosystem

#3119 contrib/internal/httptrace: add telemetry for inferred spans
  contrib/internal/httptrace/httptrace.go
Labels: apm:ecosystem

#3081 Support valkey-go tracing
  .github/workflows/unit-integration-tests.yml
  contrib/go-redis/redis.v7/redis.go
  contrib/go-redis/redis.v8/redis.go
  contrib/go-redis/redis/redis.go
  contrib/redis/go-redis.v9/redis.go
  contrib/valkey-go/example_test.go
  contrib/valkey-go/option.go
  contrib/valkey-go/valkey.go
  contrib/valkey-go/valkey_test.go
  ddtrace/ext/app_types.go
  ddtrace/ext/db.go
  ddtrace/ext/tags.go
  ddtrace/tracer/option.go
  ddtrace/tracer/option_test.go
  docker-compose.yaml
  go.mod
  go.sum
  internal/exectracetest/go.mod
  internal/exectracetest/go.sum
  internal/orchestrion/_integration/go.sum
Labels: apm:ecosystem

#3127 fix(net/http: orchestrion): obfuscate query string parameters when auto-instrumenting
  contrib/net/http/orchestrion.client.yml
  internal/orchestrion/_integration/aws.v2/base.go
Labels: apm:ecosystem
