Repository DataDog/dd-trace-go, pull requests merged in 2025-02, with the labels that each got.

#3121 contrib/gorm.io/gorm.v1: fix orchestrion aspect
  contrib/gorm.io/gorm.v1/orchestrion.yml
  internal/orchestrion/_integration/gorm/gorm.go
Labels: apm:ecosystem

#3025 contrib/database/sql: Close DB Stats goroutine on db.Close()
  contrib/database/sql/metrics.go
  contrib/database/sql/metrics_test.go
  contrib/database/sql/sql.go
  contrib/database/sql/sql_test.go
  contrib/jackc/pgx.v5/metrics.go
Labels: apm:ecosystem

#3147 [v2] port #3025 to v2
  contrib/database/sql/metrics.go
  contrib/database/sql/metrics_test.go
  contrib/database/sql/sql.go
  contrib/database/sql/sql_test.go
  contrib/jackc/pgx.v5/metrics.go
Labels: apm:ecosystem

#3164 contrib/miekg/dns: use random port for test
  contrib/miekg/dns/dns_test.go
Labels: apm:ecosystem

#3184 contrib/internal/httptrace: add inferred span identification tag
  contrib/internal/httptrace/httptrace_api_gateway_test.go
  contrib/internal/httptrace/inferred_proxy.go
Labels: apm:ecosystem

#3126 Opentelemetry Baggage Propagation
  contrib/internal/httptrace/httptrace.go
  contrib/internal/httptrace/httptrace_test.go
  contrib/net/http/roundtripper.go
  contrib/net/http/roundtripper_test.go
  ddtrace/opentelemetry/telemetry_test.go
  ddtrace/tracer/log_test.go
  ddtrace/tracer/textmap.go
  ddtrace/tracer/textmap_test.go
  ddtrace/tracer/tracer_test.go
Labels: apm:ecosystem, mergequeue-status: error

#3173 contrib: add messaging.destination.name to kafka integrations
  contrib/IBM/sarama.v1/consumer_group_test.go
  contrib/IBM/sarama.v1/consumer_test.go
  contrib/IBM/sarama.v1/dispatcher.go
  contrib/IBM/sarama.v1/producer.go
  contrib/IBM/sarama.v1/producer_test.go
  contrib/confluentinc/confluent-kafka-go/internal/tracing/consumer.go
  contrib/confluentinc/confluent-kafka-go/internal/tracing/producer.go
  contrib/confluentinc/confluent-kafka-go/kafka.v2/kafka_test.go
  contrib/confluentinc/confluent-kafka-go/kafka/kafka_test.go
  contrib/segmentio/kafka.go.v0/internal/tracing/tracing.go
  contrib/segmentio/kafka.go.v0/kafka_test.go
  ddtrace/ext/messaging.go
Labels: apm:ecosystem

#3190 all: upgrade minimum supported Go release to 1.23
  .github/workflows/appsec.yml
  .github/workflows/main-branch-tests.yml
  .github/workflows/pull-request.yml
  .github/workflows/smoke-tests.yml
  .gitlab-ci.yml
  .gitlab/macrobenchmarks.yml
  contrib/net/http/internal/wrap/get_pattern.go
  contrib/net/http/internal/wrap/get_pattern_go122.go
  go.mod
  integration_go.mod
  internal/exectracetest/go.mod
  internal/orchestrion/_integration/go.mod
  internal/setup-smoke-test/Dockerfile
  internal/setup-smoke-test/go.mod
Labels: apm:ecosystem

#3083 [serverless] Add S3 span pointers
  contrib/aws/aws-sdk-go-v2/aws/aws.go
  contrib/aws/internal/span_pointers/span_pointers.go
  contrib/aws/internal/span_pointers/span_pointers_test.go
  ddtrace/mocktracer/mockspan.go
Labels: apm:ecosystem

#3197 contrib: fix service extension tests
  contrib/envoyproxy/go-control-plane/envoy_test.go
Labels: apm:ecosystem

#3232 fix(net/http): finish the request span when RASP blocking triggers
  contrib/net/http/internal/wrap/roundtrip.go
  contrib/net/http/roundtripper_test.go
Labels: apm:ecosystem

#3230 internal: implement new tag for trace source
  .github/workflows/system-tests.yml
  ddtrace/tracer/option.go
  ddtrace/tracer/propagating_tags.go
  ddtrace/tracer/span.go
  ddtrace/tracer/tracer.go
  internal/appsec/listener/httpsec/request_test.go
  internal/appsec/listener/waf/tags.go
  internal/meta_internal_types.go
  internal/trace_source.go
  internal/trace_source_test.go
Labels: appsec, mergequeue-status: waiting

#3116 Enable 128bit trace ID logging by default
  contrib/log/slog/slog.go
  contrib/log/slog/slog_test.go
  contrib/sirupsen/logrus/logrus.go
  contrib/sirupsen/logrus/logrus_test.go
  ddtrace/tracer/log_test.go
  ddtrace/tracer/span.go
  ddtrace/tracer/span_test.go
Labels: apm:ecosystem
