Repository DataDog/dd-trace-go, pull requests merged in 2025-10, with the labels that each got.

#3912 feat(contrib/haproxy): HAProxy AAP support
  contrib/envoyproxy/go-control-plane/envoy.go
  contrib/envoyproxy/go-control-plane/envoy_http.go
  contrib/haproxy/stream-processing-offload/example_test.go
  contrib/haproxy/stream-processing-offload/go.mod
  contrib/haproxy/stream-processing-offload/go.sum
  contrib/haproxy/stream-processing-offload/haproxy.go
  contrib/haproxy/stream-processing-offload/haproxy_messages.go
  contrib/haproxy/stream-processing-offload/haproxy_test.go
  contrib/haproxy/stream-processing-offload/haproxy_utils.go
  contrib/haproxy/stream-processing-offload/hdrsbin_parser.go
  contrib/haproxy/stream-processing-offload/hdrsbin_parser_test.go
  contrib/haproxy/stream-processing-offload/request_cache.go
  contrib/k8s.io/gateway-api/request-mirror.go
  instrumentation/appsec/proxy/config.go
  instrumentation/appsec/proxy/message_processor.go
  instrumentation/appsec/proxy/request_state.go
  internal/stacktrace/contribs_generated.go
Labels: apm:ecosystem, mergequeue-status: in_progress

#4030 chore(.github/workflows): ignore label_issues in all-jobs-are-green job
  .github/workflows/all-green.yml
Labels: mergequeue-status: in_progress

#3711 feat(contrib/99designs/gqlgen): Add WithShouldStartSpanFunc option
  contrib/99designs/gqlgen/option.go
  contrib/99designs/gqlgen/tracer.go
  contrib/99designs/gqlgen/tracer_test.go
Labels: apm:ecosystem, mergequeue-status: in_progress

#4033 fix: flaky test
  ddtrace/tracer/sampler_test.go
Labels: mergequeue-status: in_progress, changelog/no-changelog

#4035 feat(envoyproxy): give the option to manipule gRPC TLS
  contrib/envoyproxy/go-control-plane/cmd/serviceextensions/README.md
  contrib/envoyproxy/go-control-plane/cmd/serviceextensions/env.go
  contrib/envoyproxy/go-control-plane/cmd/serviceextensions/main.go
  contrib/envoyproxy/go-control-plane/cmd/serviceextensions/main_test.go
  internal/env/supported_configurations.gen.go
  internal/env/supported_configurations.json
Labels: apm:ecosystem, mergequeue-status: in_progress

#4038 fix: flaky test
  ddtrace/tracer/spancontext_test.go
Labels: mergequeue-status: in_progress
