Repository DataDog/dd-trace-go, pull requests merged in 2025-06, with the labels that each got.

#3582 internal/appsec: report libdl_present configuration
  internal/appsec/appsec.go
  internal/appsec/appsec_test.go
  internal/appsec/telemetry.go
  internal/telemetry/telemetrytest/record.go
Labels: appsec

#3559 orchestrion: don't trace the tracer even if tracer.Start(tracer.WithHTTPClient(...)) is called
  contrib/net/http/orchestrion.client.yml
  ddtrace/tracer/option.go
  ddtrace/tracer/option_test.go
  internal/civisibility/utils/net/http.go
  internal/orchestrion/_integration/internal/agent/agent.go
  internal/orchestrion/_integration/internal/harness/harness.go
  internal/telemetry/internal/writer.go
Labels: bug, apm:ecosystem

#3601 contrib/envoyproxy: Add requests counter per minute
  contrib/envoyproxy/go-control-plane/cmd/serviceextensions/main.go
  contrib/envoyproxy/go-control-plane/envoy.go
Labels: apm:ecosystem

#3630 contrib/gorilla/mux: fix orchestrion aspect
  contrib/gorilla/mux/mux.go
  contrib/gorilla/mux/option.go
  contrib/gorilla/mux/orchestrion.yml
Labels: apm:ecosystem

#3631 internal/appsec: report appsec start error
  internal/appsec/appsec.go
Labels: appsec

#3550 contrib/envoyproxy: add JSON Encoder
  contrib/envoyproxy/go-control-plane/go.mod
  contrib/envoyproxy/go-control-plane/internal/json/encoder.go
  contrib/envoyproxy/go-control-plane/internal/json/encoder_test.go
  contrib/envoyproxy/go-control-plane/internal/json/unsafe.go
  go.work.sum
Labels: apm:ecosystem

#3649 contrib/database/sql: fix race condition
  contrib/database/sql/sql.go
Labels: apm:ecosystem

#3686 contrib/database/sql: sanitize sensitive data in error messages
  contrib/database/sql/internal/dsn.go
  contrib/database/sql/internal/dsn_test.go
Labels: apm:ecosystem

#3642 envoyproxy: fix misc jsoniter
  contrib/envoyproxy/go-control-plane/go.mod
  contrib/envoyproxy/go-control-plane/go.sum
  contrib/envoyproxy/go-control-plane/internal/json/encoder_test.go
  contrib/envoyproxy/go-control-plane/internal/json/jsoniter.go
  contrib/envoyproxy/go-control-plane/internal/json/simdjson.go
Labels: apm:ecosystem

#3670 envoyproxy: fix partial parsing jsoniter truncated map key
  contrib/envoyproxy/go-control-plane/internal/json/encoder_test.go
  contrib/envoyproxy/go-control-plane/internal/json/jsoniter.go
  contrib/envoyproxy/go-control-plane/internal/json/unsafe.go
Labels: apm:ecosystem

#3682 add recipe for handling flaky tests [LANGPLAT-352]
  CONTRIBUTING.md
Labels: mergequeue-status: removed

#3690 add documentation note about how to add instrumentation tests to CI [LANGPLAT-352]
  contrib/README.md
Labels: apm:ecosystem, mergequeue-status: removed

#3671 envoyproxy: body parsing support
  contrib/envoyproxy/go-control-plane/body_buffer.go
  contrib/envoyproxy/go-control-plane/cmd/serviceextensions/main.go
  contrib/envoyproxy/go-control-plane/envoy.go
  contrib/envoyproxy/go-control-plane/envoy_test.go
  contrib/envoyproxy/go-control-plane/envoy_utils.go
  contrib/envoyproxy/go-control-plane/fakehttp.go
  contrib/envoyproxy/go-control-plane/go.mod
  contrib/envoyproxy/go-control-plane/go.sum
  contrib/envoyproxy/go-control-plane/internal/json/encoder_test.go
  contrib/envoyproxy/go-control-plane/internal/json/simdjson.go
  contrib/envoyproxy/go-control-plane/message_processor.go
  contrib/envoyproxy/go-control-plane/request_state.go
  internal/appsec/testdata/user_rules.json
Labels: apm:ecosystem
