Repository DataDog/dd-trace-go, pull requests merged in 2025-07, with the labels that each got.

#3732 valkey-go: fix orchestrion schema
  .github/workflows/orchestrion.yml
  contrib/valkey-io/valkey-go/orchestrion.yml
Labels: apm:ecosystem

#3751 [chore] pin k8s version to prevent incompatible types
  scripts/ci-test-contrib.sh
Labels: apm:ecosystem

#3740 envoyproxy: remove gorilla/mux usage
  contrib/envoyproxy/go-control-plane/cmd/serviceextensions/main.go
  contrib/envoyproxy/go-control-plane/go.mod
  contrib/envoyproxy/go-control-plane/go.sum
Labels: apm:ecosystem

#3440 feat(baggage): auto-adding baggage to span tags
  instrumentation/httptrace/config.go
  instrumentation/httptrace/httptrace.go
  instrumentation/httptrace/httptrace_test.go
Labels: mergequeue-status: in_progress

#3759 contrib/envoyproxy: update default env vars
  .github/workflows/docker-build-and-push.yml
  .github/workflows/docker-images-release.yml
  contrib/envoyproxy/go-control-plane/cmd/serviceextensions/Dockerfile
  contrib/envoyproxy/go-control-plane/cmd/serviceextensions/main.go
Labels: apm:ecosystem, mergequeue-status: in_progress

#3772 ci: add STS token retrieval step for reviewdog steps
  .github/workflows/pull-request.yml
  .github/workflows/static-checks.yml
Labels: mergequeue-status: in_progress

#3778 chore(ci): Decrease initial delay for the all green check
  .github/workflows/all-green.yml
Labels: mergequeue-status: in_progress

#3783 chore(ci): use new ubuntu-24.0.4-arm runner
  .github/workflows/appsec.yml
  .github/workflows/docker-build-and-push.yml
Labels: mergequeue-status: in_progress

#3784 feat(internal/civisibility): attempt to fix v5
  internal/civisibility/constants/git.go
  internal/civisibility/integrations/civisibility_features.go
  internal/civisibility/utils/environmentTags.go
  internal/civisibility/utils/git.go
  internal/civisibility/utils/git_test.go
  internal/civisibility/utils/net/client.go
  internal/civisibility/utils/net/test_management_tests_api.go
Labels: mergequeue-status: in_progress

#3787 fix(ci): Fix STS policy for push
  .github/chainguard/self.pr-static-checks.sts.yaml
  .github/chainguard/self.push-static-checks.sts.yaml
  .github/workflows/static-checks.yml
Labels: mergequeue-status: in_progress

#3795 ci: dd-octo-sts github actions read
  .github/chainguard/gitlab.github-access.actions-read.sts.yaml
Labels: mergequeue-status: in_progress

#3792 chore(internal/civisibility): improve test suite time.
  internal/civisibility/integrations/gotesting/reflections.go
  internal/civisibility/integrations/gotesting/testcontroller_test.go
  internal/civisibility/integrations/gotesting/testing_test.go
  internal/civisibility/integrations/manual_api_mocktracer_test.go
  internal/civisibility/utils/net/http.go
  internal/civisibility/utils/net/http_test.go
Labels: mergequeue-status: in_progress

#3800 feat(internal/civisibility): update ci provider spec and add DroneCI support
  internal/civisibility/constants/git.go
  internal/civisibility/utils/ci_providers.go
  internal/civisibility/utils/ci_providers_test.go
  internal/civisibility/utils/testdata/fixtures/providers/appveyor.json
  internal/civisibility/utils/testdata/fixtures/providers/azurepipelines.json
  internal/civisibility/utils/testdata/fixtures/providers/bitbucket.json
  internal/civisibility/utils/testdata/fixtures/providers/bitrise.json
  internal/civisibility/utils/testdata/fixtures/providers/buddy.json
  internal/civisibility/utils/testdata/fixtures/providers/buildkite.json
  internal/civisibility/utils/testdata/fixtures/providers/circleci.json
  internal/civisibility/utils/testdata/fixtures/providers/codefresh.json
  internal/civisibility/utils/testdata/fixtures/providers/drone.json
  internal/civisibility/utils/testdata/fixtures/providers/github.json
  internal/civisibility/utils/testdata/fixtures/providers/gitlab.json
  internal/civisibility/utils/testdata/fixtures/providers/jenkins.json
  internal/civisibility/utils/testdata/fixtures/providers/teamcity.json
  internal/civisibility/utils/testdata/fixtures/providers/travisci.json
  internal/civisibility/utils/testdata/fixtures/providers/usersupplied.json
Labels: mergequeue-status: in_progress

#3798 fix: errorstack duration checks failing on Windows
  ddtrace/tracer/span_test.go
Labels: mergequeue-status: in_progress

#3788 chore(ddtrace/tracer): check for goroutine leaks
  CONTRIBUTING.md
  ddtrace/mocktracer/mocktracer.go
  ddtrace/mocktracer/mocktracer_test.go
  ddtrace/tracer/civisibility_transport_test.go
  ddtrace/tracer/civisibility_writer_test.go
  ddtrace/tracer/metrics_test.go
  ddtrace/tracer/option.go
  ddtrace/tracer/option_test.go
  ddtrace/tracer/sampler_test.go
  ddtrace/tracer/span_test.go
  ddtrace/tracer/spancontext_test.go
  ddtrace/tracer/telemetry.go
  ddtrace/tracer/textmap_test.go
  ddtrace/tracer/tracer.go
  ddtrace/tracer/tracer_test.go
  ddtrace/tracer/transport.go
  ddtrace/tracer/transport_test.go
  ddtrace/tracer/writer_test.go
Labels: mergequeue-status: in_progress

#3811 chore: upgrade golang.org/x/oauth2 to v0.27.0
  _tools/go.mod
  _tools/go.sum
  contrib/cloud.google.com/go/pubsub.v1/go.mod
  contrib/cloud.google.com/go/pubsub.v1/go.sum
  contrib/confluentinc/confluent-kafka-go/kafka.v2/go.mod
  contrib/confluentinc/confluent-kafka-go/kafka.v2/go.sum
  contrib/google.golang.org/api/go.mod
  contrib/google.golang.org/api/go.sum
  contrib/k8s.io/client-go/go.mod
  contrib/k8s.io/client-go/go.sum
  go.work.sum
  instrumentation/internal/namingschematest/go.sum
  instrumentation/testutils/containers/go.mod
  instrumentation/testutils/containers/go.sum
  internal/orchestrion/_integration/go.mod
  internal/orchestrion/_integration/go.sum
  orchestrion/all/go.mod
  orchestrion/all/go.sum
  tools/v2fix/go.mod
  tools/v2fix/go.sum
Labels: apm:ecosystem, mergequeue-status: in_progress

#3812 feat(internal/civisibility): add source file and codeowners tags to the suite span
  internal/civisibility/integrations/gotesting/testcontroller_test.go
  internal/civisibility/integrations/manual_api_ddtest.go
Labels: mergequeue-status: in_progress

#3813 fix(internal/civisibility): fix buildkite ci.job.id tag
  internal/civisibility/utils/ci_providers.go
  internal/civisibility/utils/testdata/fixtures/providers/awscodepipeline.json
  internal/civisibility/utils/testdata/fixtures/providers/azurepipelines.json
  internal/civisibility/utils/testdata/fixtures/providers/buildkite.json
  internal/civisibility/utils/testdata/fixtures/providers/circleci.json
  internal/civisibility/utils/testdata/fixtures/providers/github.json
  internal/civisibility/utils/testdata/fixtures/providers/gitlab.json
Labels: mergequeue-status: in_progress

#3816 fix(internal/civisibility): fix base branch SHA usage.
  internal/civisibility/constants/git.go
  internal/civisibility/utils/ci_providers.go
  internal/civisibility/utils/ci_providers_test.go
Labels: mergequeue-status: in_progress

#3823 chore(ddtrace/tracer): fix typo
  ddtrace/tracer/span.go
Labels: mergequeue-status: in_progress

#3825 ci: add new sts policies for ecosystems-label checks
  .github/chainguard/self.ecosystems-label-issue.sts.yaml
  .github/chainguard/self.ecosystems-label-pr.sts.yaml
Labels: mergequeue-status: in_progress

#3819 chore(tools): Improve develoment tool management
  .github/actions/setup-go/action.yml
  .github/workflows/api-check.yml
  .github/workflows/govulncheck.yml
  .github/workflows/multios-unit-tests.yml
  .github/workflows/orchestrion.yml
  .github/workflows/smoke-tests.yml
  .github/workflows/unit-integration-tests.yml
  .github/workflows/update-supported-versions-doc.yml
  Makefile
  _tools/README.md
  _tools/go.mod
  _tools/go.sum
  _tools/tools.go
  go.work
  go.work.sum
  instrumentation/testutils/grpc/fixturepb/gen_proto.sh
  internal/traceprof/traceproftest/bench.bash
  scripts/README.md
  scripts/check_copyright.go
  scripts/ci_contrib_matrix.go
  scripts/ci_test_contrib.sh
  scripts/ci_test_core.sh
  scripts/parseversion/parse_version.go
  scripts/parseversion/parse_version_test.go
  scripts/test.sh
  tools/v2fix/go.mod
Labels: mergequeue-status: in_progress

#3815 contrib/envoyproxy: refine component detection
  contrib/envoyproxy/go-control-plane/cmd/serviceextensions/main.go
  contrib/envoyproxy/go-control-plane/envoy.go
  contrib/envoyproxy/go-control-plane/envoy_test.go
  contrib/envoyproxy/go-control-plane/example_test.go
  contrib/envoyproxy/go-control-plane/message_processor.go
  contrib/envoyproxy/go-control-plane/request_state.go
  go.work.sum
Labels: apm:ecosystem, mergequeue-status: in_progress

#3627 feat(contrib/jackc/pgx.v5): Add WithErrCheck option
  contrib/jackc/pgx.v5/option.go
  contrib/jackc/pgx.v5/pgx_tracer.go
  contrib/jackc/pgx.v5/pgx_tracer_test.go
  ddtrace/tracer/span_config.go
Labels: apm:ecosystem
