Repository DataDog/dd-trace-go, pull requests merged in 2025-05, with the labels that each got.

#3479 feat(http): add round tripper option for status check functionality and corresponding tests
  contrib/net/http/http_test.go
  contrib/net/http/option.go
  contrib/net/http/roundtripper_test.go
Labels: apm:ecosystem

#3470 [chore] upgrade containerd to 1.7.27
  contrib/aws/aws-sdk-go-v2/go.mod
  contrib/aws/aws-sdk-go-v2/go.sum
  contrib/confluentinc/confluent-kafka-go/kafka.v2/go.mod
  contrib/confluentinc/confluent-kafka-go/kafka.v2/go.sum
  contrib/go-pg/pg.v10/go.mod
  contrib/go-pg/pg.v10/go.sum
  contrib/go-redis/redis.v7/go.mod
  contrib/go-redis/redis.v7/go.sum
  contrib/go-redis/redis.v8/go.mod
  contrib/go-redis/redis.v8/go.sum
  contrib/go-redis/redis/go.mod
  contrib/go-redis/redis/go.sum
  contrib/syndtr/goleveldb/go.mod
  contrib/syndtr/goleveldb/go.sum
  go.work.sum
  instrumentation/internal/namingschematest/go.mod
  instrumentation/internal/namingschematest/go.sum
  internal/orchestrion/_integration/go.mod
  internal/orchestrion/_integration/go.sum
  internal/tools/go.mod
  internal/tools/go.sum
  orchestrion/all/go.mod
  orchestrion/all/go.sum
Labels: apm:ecosystem

#3490 fix v2 code review issues
  contrib/confluentinc/confluent-kafka-go/kafka.v2/headers.go
  contrib/confluentinc/confluent-kafka-go/kafka.v2/kafka.go
  contrib/confluentinc/confluent-kafka-go/kafka.v2/option.go
  contrib/confluentinc/confluent-kafka-go/kafka.v2/orchestrion.yml
  contrib/confluentinc/confluent-kafka-go/kafka.v2/types.go
  contrib/confluentinc/confluent-kafka-go/kafka/headers.go
  contrib/confluentinc/confluent-kafka-go/kafka/kafka.go
  contrib/confluentinc/confluent-kafka-go/kafka/option.go
  contrib/confluentinc/confluent-kafka-go/kafka/orchestrion.yml
  contrib/confluentinc/confluent-kafka-go/kafka/types.go
  contrib/confluentinc/confluent-kafka-go/kafkatrace/consumer.go
  contrib/confluentinc/confluent-kafka-go/kafkatrace/dsm.go
  contrib/confluentinc/confluent-kafka-go/kafkatrace/kafkatrace.go
  contrib/confluentinc/confluent-kafka-go/kafkatrace/message_carrier.go
  contrib/confluentinc/confluent-kafka-go/kafkatrace/producer.go
  contrib/confluentinc/confluent-kafka-go/kafkatrace/tracer.go
  contrib/confluentinc/confluent-kafka-go/kafkatrace/tracer_test.go
  contrib/confluentinc/confluent-kafka-go/kafkatrace/types.go
  go.work.sum
  instrumentation/instrumentation.go
  instrumentation/internal/namingschematest/database_sql_test.go
  instrumentation/internal/namingschematest/gorilla_mux_test.go
  instrumentation/internal/namingschematest/graphgophers_graphql_test.go
  instrumentation/internal/namingschematest/hashicorp_consul_test.go
  instrumentation/internal/namingschematest/hashicorp_vault_test.go
  instrumentation/internal/namingschematest/ibm_sarama_test.go
  instrumentation/internal/namingschematest/julienschmidt_httprouter_test.go
  instrumentation/internal/namingschematest/labstack_echo_v4_test.go
  instrumentation/internal/namingschematest/olivere_elastic_v5_test.go
  instrumentation/internal/namingschematest/redis_goredis_v9_test.go
  instrumentation/internal/namingschematest/segmentio_kafkago_test.go
  instrumentation/internal/namingschematest/shopify_sarama_test.go
  instrumentation/internal/namingschematest/syndtr_goleveldb_test.go
  instrumentation/internal/namingschematest/tidwall_buntdb_test.go
Labels: apm:ecosystem

#3504 fix(contrib/google.golang.org/api): update tests to use ElectionQuery instead of RepresentativeInfoByAddress
  contrib/google.golang.org/api/api_test.go
Labels: apm:ecosystem

#3447 contrib/k8s.io/gateway-api: bootstrap
  .pre-commit-config.yaml
  CODEOWNERS
  contrib/k8s.io/gateway-api/example_test.go
  contrib/k8s.io/gateway-api/go.mod
  contrib/k8s.io/gateway-api/go.sum
  contrib/k8s.io/gateway-api/request-mirror.go
  go.work
  go.work.sum
  instrumentation/packages.go
Labels: apm:ecosystem

#3512 all: update go-jose dependency to v3.0.4 in multiple modules
  contrib/hashicorp/vault/go.mod
  contrib/hashicorp/vault/go.sum
  go.work.sum
  instrumentation/internal/namingschematest/go.mod
  instrumentation/internal/namingschematest/go.sum
  internal/orchestrion/_integration/go.mod
  internal/orchestrion/_integration/go.sum
  orchestrion/all/go.mod
  orchestrion/all/go.sum
Labels: apm:ecosystem

#3498 fix(baggage): drop entire baggage header when malformed
  ddtrace/tracer/textmap.go
  ddtrace/tracer/textmap_test.go
Labels: mergequeue-status: rejected

#3519 feat (internal/civisibility): Attempt to fix from v2 to v4
  internal/civisibility/integrations/gotesting/instrumentation_orchestrion.go
  internal/civisibility/integrations/gotesting/testcontroller_test.go
  internal/civisibility/integrations/gotesting/testing.go
  internal/civisibility/utils/net/test_management_tests_api.go
Labels: mergequeue-status: removed

#3486 contrib/k8s.io/gateway-api: Request mirror deployment
  .github/workflows/docker-build-and-push.yml
  contrib/k8s.io/gateway-api/README.md
  contrib/k8s.io/gateway-api/cmd/patch-gateways/main.go
  contrib/k8s.io/gateway-api/cmd/patch-httproutes/main.go
  contrib/k8s.io/gateway-api/cmd/request-mirror/Dockerfile
  contrib/k8s.io/gateway-api/cmd/request-mirror/deployment.yml
  contrib/k8s.io/gateway-api/cmd/request-mirror/example.yml
  contrib/k8s.io/gateway-api/cmd/request-mirror/main.go
  contrib/k8s.io/gateway-api/go.mod
  contrib/k8s.io/gateway-api/go.sum
  contrib/k8s.io/gateway-api/request-mirror.go
  contrib/k8s.io/gateway-api/request-mirror_test.go
  go.work.sum
Labels: apm:ecosystem, appsec

#3529 refactor(profiler): centralize compression logic
  profiler/compression.go
  profiler/compression_test.go
  profiler/metrics.go
  profiler/profile.go
  profiler/profile_test.go
  profiler/profiler.go
Labels: profiler

#3549 fix: revert unexpected changes from v1->v2
  contrib/segmentio/kafka-go/internal/tracing/tracing.go
  contrib/segmentio/kafka-go/kafka_test.go
  contrib/valkey-io/valkey-go/option.go
  internal/orchestrion/_integration/segmentio_kafka.v0/segmentio_kafka.go
  internal/orchestrion/_integration/valkey-go/valkey.go
Labels: apm:ecosystem
