Repository DataDog/dd-trace-go, pull requests merged in 2025-09, with the labels that each got.

#3935 feat(ci): enable performance SLO change tracking
  .github/chainguard/gitlab.github-access.slo-change-tracking.contents-read.sts.yaml
  .gitlab/macrobenchmarks.yml
Labels: mergequeue-status: in_progress

#3942 fix(ddtrace/tracer): move startup log after appsec has started
  ddtrace/tracer/tracer.go
Labels: mergequeue-status: in_progress

#3887 chore(.github/workflowsw): move `main` CI checks to merge queue runs
  .github/workflows/all-green.yml
  .github/workflows/appsec.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/ecosystems-label-pr.yml
  .github/workflows/generate.yml
  .github/workflows/govulncheck.yml
  .github/workflows/main-branch-tests.yml
  .github/workflows/multios-unit-tests.yml
  .github/workflows/orchestrion.yml
  .github/workflows/parametric-tests.yml
  .github/workflows/pull-request-title-validation.yml
  .github/workflows/pull-request.yml
  .github/workflows/smoke-tests.yml
  .github/workflows/static-checks.yml
  .github/workflows/system-tests.yml
  .github/workflows/unit-integration-tests.yml
  .github/workflows/update-supported-versions-doc.yml
Labels: mergequeue-status: in_progress

#3941 feat(ci): update check-slo-breaches to use a template
  .gitlab/macrobenchmarks.yml
Labels: mergequeue-status: in_progress

#3839 feat(contrib/net/http): add WithClientTimings option
  contrib/net/http/example_test.go
  contrib/net/http/internal/config/config.go
  contrib/net/http/internal/wrap/roundtrip.go
  contrib/net/http/option.go
  contrib/net/http/roundtripper_test.go
Labels: mergequeue-status: in_progress

#3933 feat: new payload interface to represent payload types
  contrib/database/sql/internal/dsn.go
  ddtrace/tracer/civisibility_payload.go
  ddtrace/tracer/civisibility_payload_test.go
  ddtrace/tracer/civisibility_transport.go
  ddtrace/tracer/civisibility_transport_test.go
  ddtrace/tracer/civisibility_writer.go
  ddtrace/tracer/civisibility_writer_test.go
  ddtrace/tracer/option.go
  ddtrace/tracer/payload.go
  ddtrace/tracer/payload_test.go
  ddtrace/tracer/payload_v04.go
  ddtrace/tracer/payload_v1.go
  ddtrace/tracer/span_test.go
  ddtrace/tracer/tracer_test.go
  ddtrace/tracer/transport.go
  ddtrace/tracer/transport_bench_test.go
  ddtrace/tracer/transport_test.go
  ddtrace/tracer/writer.go
  ddtrace/tracer/writer_bench_test.go
  ddtrace/tracer/writer_test.go
  profiler/profiler.go
  profiler/profiler_test.go
Labels: apm:ecosystem

#3963 ci: update import url for one-pipeline scripts
  .gitlab/configuration-central-validation.yml
Labels: mergequeue-status: in_progress

#3951 chore(instrumentation/appsec): move code from envoy to instrumentation for API10 and HAProxy
  contrib/envoyproxy/go-control-plane/envoy.go
  contrib/envoyproxy/go-control-plane/envoy_http.go
  contrib/envoyproxy/go-control-plane/envoy_messages.go
  contrib/envoyproxy/go-control-plane/go.mod
  go.mod
  go.sum
  instrumentation/appsec/proxy/body_buffer.go
  instrumentation/appsec/proxy/config.go
  instrumentation/appsec/proxy/fakehttp.go
  instrumentation/appsec/proxy/interfaces.go
  instrumentation/appsec/proxy/message_processor.go
  instrumentation/appsec/proxy/metrics.go
  instrumentation/appsec/proxy/request_state.go
  internal/appsec/body/json/encoder_test.go
  internal/appsec/body/json/jsoniter.go
  internal/appsec/body/json/simdjson.go
  internal/appsec/body/json/unsafe.go
Labels: apm:ecosystem, mergequeue-status: in_progress

#3986 feat(contrib/haproxy): start empty haproxy contrib
  CODEOWNERS
  contrib/haproxy/stream-processing-offload/go.mod
  contrib/haproxy/stream-processing-offload/go.sum
  contrib/haproxy/stream-processing-offload/haproxy.go
  go.work
  instrumentation/packages.go
Labels: apm:ecosystem, mergequeue-status: removed

#3950 chore: update CODEOWNERS with apm-sdk-api-go team
  CODEOWNERS
Labels: mergequeue-status: in_progress

#3966 feat(aws): add partition tag
  contrib/aws/aws-sdk-go-v2/aws/aws.go
  contrib/aws/aws-sdk-go-v2/aws/aws_test.go
  contrib/aws/aws-sdk-go/aws/aws.go
  contrib/aws/aws-sdk-go/aws/aws_test.go
  ddtrace/ext/aws.go
Labels: apm:ecosystem, mergequeue-status: in_progress

#3943 feat: datadog-lambda-go
  CODEOWNERS
  contrib/aws/datadog-lambda-go/awslambdanorpc.go
  contrib/aws/datadog-lambda-go/awslambdawithrpc.go
  contrib/aws/datadog-lambda-go/ddlambda.go
  contrib/aws/datadog-lambda-go/ddlambda_example_test.go
  contrib/aws/datadog-lambda-go/ddlambda_test.go
  contrib/aws/datadog-lambda-go/go.mod
  contrib/aws/datadog-lambda-go/go.sum
  contrib/aws/datadog-lambda-go/internal/extension/extension.go
  contrib/aws/datadog-lambda-go/internal/extension/extension_test.go
  contrib/aws/datadog-lambda-go/internal/internal.go
  contrib/aws/datadog-lambda-go/internal/logger/log.go
  contrib/aws/datadog-lambda-go/internal/metrics/api.go
  contrib/aws/datadog-lambda-go/internal/metrics/api_test.go
  contrib/aws/datadog-lambda-go/internal/metrics/batcher.go
  contrib/aws/datadog-lambda-go/internal/metrics/batcher_test.go
  contrib/aws/datadog-lambda-go/internal/metrics/constants.go
  contrib/aws/datadog-lambda-go/internal/metrics/context.go
  contrib/aws/datadog-lambda-go/internal/metrics/context_test.go
  contrib/aws/datadog-lambda-go/internal/metrics/kms_decrypter.go
  contrib/aws/datadog-lambda-go/internal/metrics/kms_decrypter_test.go
  contrib/aws/datadog-lambda-go/internal/metrics/listener.go
  contrib/aws/datadog-lambda-go/internal/metrics/listener_test.go
  contrib/aws/datadog-lambda-go/internal/metrics/model.go
  contrib/aws/datadog-lambda-go/internal/metrics/processor.go
  contrib/aws/datadog-lambda-go/internal/metrics/processor_test.go
  contrib/aws/datadog-lambda-go/internal/metrics/time.go
  contrib/aws/datadog-lambda-go/internal/testdata/apig-event-no-headers.json
  contrib/aws/datadog-lambda-go/internal/testdata/apig-event-with-headers.json
  contrib/aws/datadog-lambda-go/internal/testdata/invalid.json
  contrib/aws/datadog-lambda-go/internal/testdata/non-proxy-no-headers.json
  contrib/aws/datadog-lambda-go/internal/testdata/non-proxy-with-headers.json
  contrib/aws/datadog-lambda-go/internal/testdata/non-proxy-with-missing-sampling-priority.json
  contrib/aws/datadog-lambda-go/internal/testdata/non-proxy-with-mixed-case-headers.json
  contrib/aws/datadog-lambda-go/internal/trace/constants.go
  contrib/aws/datadog-lambda-go/internal/trace/context.go
  contrib/aws/datadog-lambda-go/internal/trace/context_test.go
  contrib/aws/datadog-lambda-go/internal/trace/listener.go
  contrib/aws/datadog-lambda-go/internal/trace/listener_test.go
  contrib/aws/datadog-lambda-go/internal/wrapper/wrap_handler.go
  contrib/aws/datadog-lambda-go/internal/wrapper/wrap_handler_test.go
  go.work
  go.work.sum
  instrumentation/instrumentation_test.go
  instrumentation/packages.go
  internal/stacktrace/contribs_generated.go
Labels: apm:ecosystem, mergequeue-status: in_progress, serverless

#3992 chore(ci): replace TELEMETRY_METRIC_GENERATION_ENABLED with AGENT_SUPPORTING_SPAN_EVENTS from system-tests
  .github/workflows/system-tests.yml
Labels: mergequeue-status: in_progress

#4000 fix(ddtrace/tracer): TestSpansStartedTags
  ddtrace/tracer/metrics_test.go
Labels: mergequeue-status: in_progress, Bits AI

#3953 chore: remove garyburd/redigo dependency
  contrib/hashicorp/vault/go.mod
  contrib/hashicorp/vault/go.sum
  go.work.sum
  instrumentation/internal/namingschematest/go.mod
  instrumentation/internal/namingschematest/go.sum
  internal/orchestrion/_integration/go.mod
  internal/orchestrion/_integration/go.sum
  internal/stacktrace/contribs_generated.go
  orchestrion/all/go.mod
  orchestrion/all/go.sum
  tools/v2fix/_stage/go.mod
  tools/v2fix/_stage/go.sum
  tools/v2fix/go.mod
  tools/v2fix/go.sum
Labels: apm:ecosystem, mergequeue-status: in_progress
